// Auto-generated extension model for @swamp/cloudflare/urlscanner/scan
// Do not edit manually. Re-generate with: deno task generate:cloudflare

// deno-lint-ignore-file no-explicit-any

/**
 * Swamp extension model for a Cloudflare Scan.
 *
 * Wraps the Cloudflare API as a swamp model so create, get, update,
 * delete, and sync can be driven through `swamp model`.
 *
 * @module
 */

import { z } from "npm:zod@4.3.6";
import { create, read, tryRead } from "./_lib/cloudflare.ts";

const GlobalArgsSchema = z.object({
  account_id: z.string().describe("Cloudflare account ID"),
  name: z.string().describe(
    "Instance name for this resource (used as the unique identifier in the factory pattern)",
  ),
  country: z.enum([
    "AF",
    "AL",
    "DZ",
    "AD",
    "AO",
    "AG",
    "AR",
    "AM",
    "AU",
    "AT",
    "AZ",
    "BH",
    "BD",
    "BB",
    "BY",
    "BE",
    "BZ",
    "BJ",
    "BM",
    "BT",
    "BO",
    "BA",
    "BW",
    "BR",
    "BN",
    "BG",
    "BF",
    "BI",
    "KH",
    "CM",
    "CA",
    "CV",
    "KY",
    "CF",
    "TD",
    "CL",
    "CN",
    "CO",
    "KM",
    "CG",
    "CR",
    "CI",
    "HR",
    "CU",
    "CY",
    "CZ",
    "CD",
    "DK",
    "DJ",
    "DM",
    "DO",
    "EC",
    "EG",
    "SV",
    "GQ",
    "ER",
    "EE",
    "SZ",
    "ET",
    "FJ",
    "FI",
    "FR",
    "GA",
    "GE",
    "DE",
    "GH",
    "GR",
    "GL",
    "GD",
    "GT",
    "GN",
    "GW",
    "GY",
    "HT",
    "HN",
    "HU",
    "IS",
    "IN",
    "ID",
    "IR",
    "IQ",
    "IE",
    "IL",
    "IT",
    "JM",
    "JP",
    "JO",
    "KZ",
    "KE",
    "KI",
    "KW",
    "KG",
    "LA",
    "LV",
    "LB",
    "LS",
    "LR",
    "LY",
    "LI",
    "LT",
    "LU",
    "MO",
    "MG",
    "MW",
    "MY",
    "MV",
    "ML",
    "MR",
    "MU",
    "MX",
    "FM",
    "MD",
    "MC",
    "MN",
    "MS",
    "MA",
    "MZ",
    "MM",
    "NA",
    "NR",
    "NP",
    "NL",
    "NZ",
    "NI",
    "NE",
    "NG",
    "KP",
    "MK",
    "NO",
    "OM",
    "PK",
    "PS",
    "PA",
    "PG",
    "PY",
    "PE",
    "PH",
    "PL",
    "PT",
    "QA",
    "RO",
    "RU",
    "RW",
    "SH",
    "KN",
    "LC",
    "VC",
    "WS",
    "SM",
    "ST",
    "SA",
    "SN",
    "RS",
    "SC",
    "SL",
    "SK",
    "SI",
    "SB",
    "SO",
    "ZA",
    "KR",
    "SS",
    "ES",
    "LK",
    "SD",
    "SR",
    "SE",
    "CH",
    "SY",
    "TW",
    "TJ",
    "TZ",
    "TH",
    "BS",
    "GM",
    "TL",
    "TG",
    "TO",
    "TT",
    "TN",
    "TR",
    "TM",
    "UG",
    "UA",
    "AE",
    "GB",
    "US",
    "UY",
    "UZ",
    "VU",
    "VE",
    "VN",
    "YE",
    "ZM",
    "ZW",
  ]).describe("Country to geo egress from").optional(),
  customHeaders: z.record(z.string(), z.unknown()).describe(
    "Set custom headers.",
  ).optional(),
  screenshotsResolutions: z.array(z.enum(["desktop", "mobile", "tablet"]))
    .describe("Take multiple screenshots targeting different device types.")
    .optional(),
  url: z.string(),
  visibility: z.enum(["Public", "Unlisted"]).describe(
    "The option `Public` means it will be included in listings like recent scans and search results. `Unlisted` means it will not be included in the aforementioned listings, users will need to have the scan's ID to access it. A a scan will be automatically marked as unlisted if it fails, if it contains potential PII or other sensitive material.",
  ).optional(),
});

const ResourceSchema = z.object({
  scan: z.object({
    asns: z.object({
      asn: z.object({
        asn: z.string().optional(),
        description: z.string().optional(),
        location_alpha2: z.string().optional(),
        name: z.string().optional(),
        org_name: z.string().optional(),
      }).optional(),
    }).optional(),
    certificates: z.array(z.object({
      issuer: z.string().optional(),
      subjectName: z.string().optional(),
      validFrom: z.number().optional(),
      validTo: z.number().optional(),
    })).optional(),
    domains: z.object({
      "example.com": z.object({
        categories: z.object({
          content: z.array(z.object({
            id: z.number().optional(),
            name: z.string().optional(),
            super_category_id: z.number().optional(),
          })).optional(),
          inherited: z.object({
            content: z.array(z.object({
              id: z.number().optional(),
              name: z.string().optional(),
              super_category_id: z.number().optional(),
            })).optional(),
            from: z.string().optional(),
            risks: z.array(z.object({
              id: z.number().optional(),
              name: z.string().optional(),
              super_category_id: z.number().optional(),
            })).optional(),
          }).optional(),
          risks: z.array(z.object({
            id: z.number().optional(),
            name: z.string().optional(),
            super_category_id: z.number().optional(),
          })).optional(),
        }).optional(),
        dns: z.array(z.object({
          address: z.string().optional(),
          dnssec_valid: z.boolean().optional(),
          name: z.string().optional(),
          type: z.string().optional(),
        })).optional(),
        name: z.string().optional(),
        rank: z.object({
          bucket: z.string().optional(),
          name: z.string().optional(),
          rank: z.number().optional(),
        }).optional(),
        type: z.string().optional(),
      }).optional(),
    }).optional(),
    geo: z.object({
      continents: z.array(z.string()).optional(),
      locations: z.array(z.string()).optional(),
    }).optional(),
    ips: z.object({
      ip: z.object({
        asn: z.string().optional(),
        asnDescription: z.string().optional(),
        asnLocationAlpha2: z.string().optional(),
        asnName: z.string().optional(),
        asnOrgName: z.string().optional(),
        continent: z.string().optional(),
        geonameId: z.string().optional(),
        ip: z.string().optional(),
        ipVersion: z.string().optional(),
        latitude: z.string().optional(),
        locationAlpha2: z.string().optional(),
        locationName: z.string().optional(),
        longitude: z.string().optional(),
        subdivision1Name: z.string().optional(),
        subdivision2Name: z.string().optional(),
      }).optional(),
    }).optional(),
    links: z.object({
      link: z.object({
        href: z.string().optional(),
        text: z.string().optional(),
      }).optional(),
    }).optional(),
    meta: z.object({
      processors: z.object({
        categories: z.object({
          content: z.array(z.object({
            id: z.number().optional(),
            name: z.string().optional(),
            super_category_id: z.number().optional(),
          })).optional(),
          risks: z.array(z.object({
            id: z.number().optional(),
            name: z.string().optional(),
            super_category_id: z.number().optional(),
          })).optional(),
        }).optional(),
        phishing: z.array(z.string()).optional(),
        rank: z.object({
          bucket: z.string().optional(),
          name: z.string().optional(),
          rank: z.number().optional(),
        }).optional(),
        tech: z.array(z.object({
          categories: z.array(z.object({
            groups: z.array(z.number()).optional(),
            id: z.number().optional(),
            name: z.string().optional(),
            priority: z.number().optional(),
            slug: z.string().optional(),
          })).optional(),
          confidence: z.number().optional(),
          description: z.string().optional(),
          evidence: z.object({
            impliedBy: z.array(z.string()).optional(),
            patterns: z.array(z.object({
              confidence: z.number().optional(),
              excludes: z.array(z.string()).optional(),
              implies: z.array(z.string()).optional(),
              match: z.string().optional(),
              name: z.string().optional(),
              regex: z.string().optional(),
              type: z.string().optional(),
              value: z.string().optional(),
              version: z.string().optional(),
            })).optional(),
          }).optional(),
          icon: z.string().optional(),
          name: z.string().optional(),
          slug: z.string().optional(),
          website: z.string().optional(),
        })).optional(),
      }).optional(),
    }).optional(),
    page: z.object({
      asn: z.string().optional(),
      asnLocationAlpha2: z.string().optional(),
      asnname: z.string().optional(),
      console: z.array(z.object({
        category: z.string().optional(),
        text: z.string().optional(),
        type: z.string().optional(),
        url: z.string().optional(),
      })).optional(),
      cookies: z.array(z.object({
        domain: z.string().optional(),
        expires: z.number().optional(),
        httpOnly: z.boolean().optional(),
        name: z.string().optional(),
        path: z.string().optional(),
        priority: z.string().optional(),
        sameParty: z.boolean().optional(),
        secure: z.boolean().optional(),
        session: z.boolean().optional(),
        size: z.number().optional(),
        sourcePort: z.number().optional(),
        sourceScheme: z.string().optional(),
        value: z.string().optional(),
      })).optional(),
      country: z.string().optional(),
      countryLocationAlpha2: z.string().optional(),
      domain: z.string().optional(),
      headers: z.array(z.object({
        name: z.string().optional(),
        value: z.string().optional(),
      })).optional(),
      ip: z.string().optional(),
      js: z.object({
        variables: z.array(z.object({
          name: z.string().optional(),
          type: z.string().optional(),
        })).optional(),
      }).optional(),
      securityViolations: z.array(z.object({
        category: z.string().optional(),
        text: z.string().optional(),
        url: z.string().optional(),
      })).optional(),
      status: z.number().optional(),
      subdivision1Name: z.string().optional(),
      subdivision2name: z.string().optional(),
      url: z.string().optional(),
    }).optional(),
    performance: z.array(z.object({
      connectEnd: z.number().optional(),
      connectStart: z.number().optional(),
      decodedBodySize: z.number().optional(),
      domComplete: z.number().optional(),
      domContentLoadedEventEnd: z.number().optional(),
      domContentLoadedEventStart: z.number().optional(),
      domInteractive: z.number().optional(),
      domainLookupEnd: z.number().optional(),
      domainLookupStart: z.number().optional(),
      duration: z.number().optional(),
      encodedBodySize: z.number().optional(),
      entryType: z.string().optional(),
      fetchStart: z.number().optional(),
      initiatorType: z.string().optional(),
      loadEventEnd: z.number().optional(),
      loadEventStart: z.number().optional(),
      name: z.string().optional(),
      nextHopProtocol: z.string().optional(),
      redirectCount: z.number().optional(),
      redirectEnd: z.number().optional(),
      redirectStart: z.number().optional(),
      requestStart: z.number().optional(),
      responseEnd: z.number().optional(),
      responseStart: z.number().optional(),
      secureConnectionStart: z.number().optional(),
      startTime: z.number().optional(),
      transferSize: z.number().optional(),
      type: z.string().optional(),
      unloadEventEnd: z.number().optional(),
      unloadEventStart: z.number().optional(),
      workerStart: z.number().optional(),
    })).optional(),
    task: z.object({
      clientLocation: z.string().optional(),
      clientType: z.string().optional(),
      effectiveUrl: z.string().optional(),
      errors: z.array(z.object({
        message: z.string().optional(),
      })).optional(),
      scannedFrom: z.object({
        colo: z.string().optional(),
      }).optional(),
      status: z.string().optional(),
      success: z.boolean().optional(),
      time: z.string().optional(),
      timeEnd: z.string().optional(),
      url: z.string().optional(),
      uuid: z.string().optional(),
      visibility: z.string().optional(),
    }).optional(),
    verdicts: z.object({
      overall: z.object({
        categories: z.array(z.object({
          id: z.number().optional(),
          name: z.string().optional(),
          super_category_id: z.number().optional(),
        })).optional(),
        malicious: z.boolean().optional(),
        phishing: z.array(z.string()).optional(),
      }).optional(),
    }).optional(),
  }).optional(),
  id: z.string(),
}).passthrough();

type ResourceData = z.infer<typeof ResourceSchema>;

const InputsSchema = z.object({
  account_id: z.string().optional(),
  name: z.string().optional(),
  country: z.enum([
    "AF",
    "AL",
    "DZ",
    "AD",
    "AO",
    "AG",
    "AR",
    "AM",
    "AU",
    "AT",
    "AZ",
    "BH",
    "BD",
    "BB",
    "BY",
    "BE",
    "BZ",
    "BJ",
    "BM",
    "BT",
    "BO",
    "BA",
    "BW",
    "BR",
    "BN",
    "BG",
    "BF",
    "BI",
    "KH",
    "CM",
    "CA",
    "CV",
    "KY",
    "CF",
    "TD",
    "CL",
    "CN",
    "CO",
    "KM",
    "CG",
    "CR",
    "CI",
    "HR",
    "CU",
    "CY",
    "CZ",
    "CD",
    "DK",
    "DJ",
    "DM",
    "DO",
    "EC",
    "EG",
    "SV",
    "GQ",
    "ER",
    "EE",
    "SZ",
    "ET",
    "FJ",
    "FI",
    "FR",
    "GA",
    "GE",
    "DE",
    "GH",
    "GR",
    "GL",
    "GD",
    "GT",
    "GN",
    "GW",
    "GY",
    "HT",
    "HN",
    "HU",
    "IS",
    "IN",
    "ID",
    "IR",
    "IQ",
    "IE",
    "IL",
    "IT",
    "JM",
    "JP",
    "JO",
    "KZ",
    "KE",
    "KI",
    "KW",
    "KG",
    "LA",
    "LV",
    "LB",
    "LS",
    "LR",
    "LY",
    "LI",
    "LT",
    "LU",
    "MO",
    "MG",
    "MW",
    "MY",
    "MV",
    "ML",
    "MR",
    "MU",
    "MX",
    "FM",
    "MD",
    "MC",
    "MN",
    "MS",
    "MA",
    "MZ",
    "MM",
    "NA",
    "NR",
    "NP",
    "NL",
    "NZ",
    "NI",
    "NE",
    "NG",
    "KP",
    "MK",
    "NO",
    "OM",
    "PK",
    "PS",
    "PA",
    "PG",
    "PY",
    "PE",
    "PH",
    "PL",
    "PT",
    "QA",
    "RO",
    "RU",
    "RW",
    "SH",
    "KN",
    "LC",
    "VC",
    "WS",
    "SM",
    "ST",
    "SA",
    "SN",
    "RS",
    "SC",
    "SL",
    "SK",
    "SI",
    "SB",
    "SO",
    "ZA",
    "KR",
    "SS",
    "ES",
    "LK",
    "SD",
    "SR",
    "SE",
    "CH",
    "SY",
    "TW",
    "TJ",
    "TZ",
    "TH",
    "BS",
    "GM",
    "TL",
    "TG",
    "TO",
    "TT",
    "TN",
    "TR",
    "TM",
    "UG",
    "UA",
    "AE",
    "GB",
    "US",
    "UY",
    "UZ",
    "VU",
    "VE",
    "VN",
    "YE",
    "ZM",
    "ZW",
  ]).optional(),
  customHeaders: z.record(z.string(), z.unknown()).optional(),
  screenshotsResolutions: z.array(z.enum(["desktop", "mobile", "tablet"]))
    .optional(),
  url: z.string().optional(),
  visibility: z.enum(["Public", "Unlisted"]).optional(),
});

/** Swamp extension model for Cloudflare Scan. Registered at `@swamp/cloudflare/urlscanner/scan`. */
export const model = {
  type: "@swamp/cloudflare/urlscanner/scan",
  version: "2026.05.22.1",
  globalArguments: GlobalArgsSchema,
  inputsSchema: InputsSchema,
  resources: {
    state: {
      description: "Scan resource state",
      schema: ResourceSchema,
      lifetime: "infinite",
      garbageCollection: 10,
    },
  },
  methods: {
    create: {
      description: "Create a Scan",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const endpoint = "/accounts/" + g.account_id + "/urlscanner/scan";
        const body: Record<string, unknown> = {};
        if (g.country !== undefined) body.country = g.country;
        if (g.customHeaders !== undefined) body.customHeaders = g.customHeaders;
        if (g.screenshotsResolutions !== undefined) {
          body.screenshotsResolutions = g.screenshotsResolutions;
        }
        if (g.url !== undefined) body.url = g.url;
        if (g.visibility !== undefined) body.visibility = g.visibility;
        const result = await create(endpoint, body) as ResourceData;
        const instanceName = (g.name?.toString() ?? "current").replace(
          /[\/\\]/g,
          "_",
        ).replace(/\.\./g, "_").replace(/\0/g, "");
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    get: {
      description: "Get a Scan",
      arguments: z.object({ id: z.string().describe("The ID of the Scan") }),
      execute: async (args: { id: string }, context: any) => {
        const g = context.globalArgs;
        const endpoint = "/accounts/" + g.account_id + "/urlscanner/scan";
        const result = await read(endpoint, args.id) as ResourceData;
        const instanceName = (g.name?.toString() ?? args.id).replace(
          /[\/\\]/g,
          "_",
        ).replace(/\.\./g, "_").replace(/\0/g, "");
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    sync: {
      description: "Sync Scan state from Cloudflare",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const endpoint = "/accounts/" + g.account_id + "/urlscanner/scan";
        const instanceName = (g.name?.toString() ?? "current").replace(
          /[\/\\]/g,
          "_",
        ).replace(/\.\./g, "_").replace(/\0/g, "");
        const content = await context.dataRepository.getContent(
          context.modelType,
          context.modelId,
          instanceName,
        );
        if (!content) {
          throw new Error("No data found - run create or get first");
        }
        const existing = JSON.parse(new TextDecoder().decode(content));
        if (!existing.id) {
          throw new Error("Stored state has no id - cannot sync");
        }
        const result = await tryRead(endpoint, existing.id) as
          | ResourceData
          | null;
        if (result) {
          const handle = await context.writeResource(
            "state",
            instanceName,
            result,
          );
          return { dataHandles: [handle] };
        }
        const handle = await context.writeResource("state", instanceName, {
          id: existing.id,
          status: "not_found",
          syncedAt: new Date().toISOString(),
        });
        return { dataHandles: [handle] };
      },
    },
  },
};
