// Swamp, an Automation Framework
// Copyright (C) 2026 Elder Swamp Club, Inc.
//
// This file is part of Swamp.
//
// Swamp is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License version 3
// as published by the Free Software Foundation, with the Swamp
// Extension and Definition Exception (found in the "COPYING-EXCEPTION"
// file).
//
// Swamp is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with Swamp.  If not, see <https://www.gnu.org/licenses/>.

// Auto-generated extension model for @swamp/aws/elasticache/global-replication-group
// Do not edit manually. Re-generate with: deno task generate:aws

// deno-lint-ignore-file no-explicit-any

/**
 * Swamp extension model for ElastiCache GlobalReplicationGroup (AWS::ElastiCache::GlobalReplicationGroup).
 *
 * Wraps the CloudFormation resource type as a swamp model so create,
 * get, update, delete, and sync can be driven through `swamp model`.
 *
 * @module
 */

import { z } from "npm:zod@4.3.6";
import {
  createResource,
  deleteResource,
  isResourceNotFoundError,
  readResource,
  updateResource,
} from "./_lib/aws.ts";
import type { AwsCredentials } from "./_lib/aws.ts";

const GlobalReplicationGroupMemberSchema = z.object({
  ReplicationGroupId: z.string().describe(
    "Regionally unique identifier for the member i.e. ReplicationGroupId.",
  ).optional(),
  ReplicationGroupRegion: z.string().describe(
    "The AWS region of the Global Datastore member.",
  ).optional(),
  Role: z.enum(["PRIMARY", "SECONDARY"]).describe(
    "Indicates the role of the member, primary or secondary.",
  ).optional(),
});

const ReshardingConfigurationSchema = z.object({
  NodeGroupId: z.string().describe(
    "Unique identifier for the Node Group. This is either auto-generated by ElastiCache (4-digit id) or a user supplied id.",
  ).optional(),
  PreferredAvailabilityZones: z.array(z.string()).describe(
    "A list of preferred availability zones for the nodes of new node groups.",
  ).optional(),
});

const RegionalConfigurationSchema = z.object({
  ReplicationGroupId: z.string().describe(
    "The replication group id of the Global Datastore member.",
  ).optional(),
  ReplicationGroupRegion: z.string().describe(
    "The AWS region of the Global Datastore member.",
  ).optional(),
  ReshardingConfigurations: z.array(ReshardingConfigurationSchema).describe(
    "A list of PreferredAvailabilityZones objects that specifies the configuration of a node group in the resharded cluster.",
  ).optional(),
});

const GlobalArgsSchema = z.object({
  name: z.string().describe(
    "Instance name for this resource (used as the unique identifier in the factory pattern)",
  ),
  accessKeyId: z.string().meta({ sensitive: true }).describe(
    "AWS access key ID; overrides AWS_ACCESS_KEY_ID environment variable. Wire with a vault.get(...) expression to source it from a vault.",
  ).optional(),
  secretAccessKey: z.string().meta({ sensitive: true }).describe(
    "AWS secret access key; overrides AWS_SECRET_ACCESS_KEY environment variable. Wire with a vault.get(...) expression to source it from a vault.",
  ).optional(),
  sessionToken: z.string().meta({ sensitive: true }).describe(
    "AWS session token for temporary credentials; overrides AWS_SESSION_TOKEN environment variable. Wire with a vault.get(...) expression to source it from a vault.",
  ).optional(),
  region: z.string().describe(
    "AWS region; overrides AWS_REGION / AWS_DEFAULT_REGION environment variables and ~/.aws/config profile region. Defaults to us-east-1.",
  ).optional(),
  GlobalReplicationGroupIdSuffix: z.string().describe(
    "The suffix name of a Global Datastore. Amazon ElastiCache automatically applies a prefix to the Global Datastore ID when it is created. Each AWS Region has its own prefix.",
  ).optional(),
  AutomaticFailoverEnabled: z.boolean().describe("AutomaticFailoverEnabled")
    .optional(),
  CacheNodeType: z.string().describe(
    "The cache node type of the Global Datastore",
  ).optional(),
  EngineVersion: z.string().describe(
    "The engine version of the Global Datastore.",
  ).optional(),
  Engine: z.string().describe("The engine of the Global Datastore.").optional(),
  CacheParameterGroupName: z.string().describe(
    "Cache parameter group name to use for the new engine version. This parameter cannot be modified independently.",
  ).optional(),
  GlobalNodeGroupCount: z.number().int().describe(
    "Indicates the number of node groups in the Global Datastore.",
  ).optional(),
  GlobalReplicationGroupDescription: z.string().describe(
    "The optional description of the Global Datastore",
  ).optional(),
  Members: z.array(GlobalReplicationGroupMemberSchema).describe(
    "The replication groups that comprise the Global Datastore.",
  ),
  RegionalConfigurations: z.array(RegionalConfigurationSchema).describe(
    "Describes the replication group IDs, the AWS regions where they are stored and the shard configuration for each that comprise the Global Datastore",
  ).optional(),
});

const StateSchema = z.object({
  GlobalReplicationGroupIdSuffix: z.string().optional(),
  AutomaticFailoverEnabled: z.boolean().optional(),
  CacheNodeType: z.string().optional(),
  EngineVersion: z.string().optional(),
  Engine: z.string().optional(),
  CacheParameterGroupName: z.string().optional(),
  GlobalNodeGroupCount: z.number().optional(),
  GlobalReplicationGroupDescription: z.string().optional(),
  GlobalReplicationGroupId: z.string(),
  Members: z.array(GlobalReplicationGroupMemberSchema).optional(),
  Status: z.string().optional(),
  RegionalConfigurations: z.array(RegionalConfigurationSchema).optional(),
}).passthrough();

type StateData = z.infer<typeof StateSchema>;

const InputsSchema = z.object({
  name: z.string().optional(),
  accessKeyId: z.string().meta({ sensitive: true }).optional(),
  secretAccessKey: z.string().meta({ sensitive: true }).optional(),
  sessionToken: z.string().meta({ sensitive: true }).optional(),
  region: z.string().optional(),
  GlobalReplicationGroupIdSuffix: z.string().describe(
    "The suffix name of a Global Datastore. Amazon ElastiCache automatically applies a prefix to the Global Datastore ID when it is created. Each AWS Region has its own prefix.",
  ).optional(),
  AutomaticFailoverEnabled: z.boolean().describe("AutomaticFailoverEnabled")
    .optional(),
  CacheNodeType: z.string().describe(
    "The cache node type of the Global Datastore",
  ).optional(),
  EngineVersion: z.string().describe(
    "The engine version of the Global Datastore.",
  ).optional(),
  Engine: z.string().describe("The engine of the Global Datastore.").optional(),
  CacheParameterGroupName: z.string().describe(
    "Cache parameter group name to use for the new engine version. This parameter cannot be modified independently.",
  ).optional(),
  GlobalNodeGroupCount: z.number().int().describe(
    "Indicates the number of node groups in the Global Datastore.",
  ).optional(),
  GlobalReplicationGroupDescription: z.string().describe(
    "The optional description of the Global Datastore",
  ).optional(),
  Members: z.array(GlobalReplicationGroupMemberSchema).describe(
    "The replication groups that comprise the Global Datastore.",
  ).optional(),
  RegionalConfigurations: z.array(RegionalConfigurationSchema).describe(
    "Describes the replication group IDs, the AWS regions where they are stored and the shard configuration for each that comprise the Global Datastore",
  ).optional(),
});

const _credentialKeys = new Set([
  "accessKeyId",
  "secretAccessKey",
  "sessionToken",
  "region",
]);

function _buildCredentials(g: Record<string, unknown>): AwsCredentials {
  return {
    accessKeyId: g.accessKeyId as string | undefined,
    secretAccessKey: g.secretAccessKey as string | undefined,
    sessionToken: g.sessionToken as string | undefined,
    region: g.region as string | undefined,
  };
}

/** Swamp extension model for ElastiCache GlobalReplicationGroup. Registered at `@swamp/aws/elasticache/global-replication-group`. */
export const model = {
  type: "@swamp/aws/elasticache/global-replication-group",
  version: "2026.06.15.1",
  upgrades: [
    {
      toVersion: "2026.04.01.1",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.04.03.1",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.04.03.2",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.04.23.1",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.04.23.2",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.06.06.1",
      description: "Added: accessKeyId, secretAccessKey, sessionToken, region",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.06.08.1",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.06.15.1",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
  ],
  globalArguments: GlobalArgsSchema,
  inputsSchema: InputsSchema,
  resources: {
    state: {
      description: "ElastiCache GlobalReplicationGroup resource state",
      schema: StateSchema,
      lifetime: "infinite",
      garbageCollection: 10,
    },
  },
  methods: {
    create: {
      description: "Create a ElastiCache GlobalReplicationGroup",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const credentials = _buildCredentials(g);
        const desiredState: Record<string, unknown> = {};
        for (const [key, value] of Object.entries(g)) {
          if (key === "name") continue;
          if (_credentialKeys.has(key)) continue;
          if (value !== undefined) desiredState[key] = value;
        }
        const result = await createResource(
          "AWS::ElastiCache::GlobalReplicationGroup",
          desiredState,
          credentials,
        ) as StateData;
        const instanceName = (g.name?.toString() ?? "current").replace(
          /[\/\\]/g,
          "_",
        ).replace(/\.\./g, "_").replace(/\0/g, "");
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    get: {
      description: "Get a ElastiCache GlobalReplicationGroup",
      arguments: z.object({
        identifier: z.string().describe(
          "The primary identifier of the ElastiCache GlobalReplicationGroup",
        ),
      }),
      execute: async (args: { identifier: string }, context: any) => {
        const credentials = _buildCredentials(context.globalArgs);
        const result = await readResource(
          "AWS::ElastiCache::GlobalReplicationGroup",
          args.identifier,
          credentials,
        ) as StateData;
        const instanceName =
          (context.globalArgs.name?.toString() ?? args.identifier).replace(
            /[\/\\]/g,
            "_",
          ).replace(/\.\./g, "_").replace(/\0/g, "");
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    update: {
      description: "Update a ElastiCache GlobalReplicationGroup",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const credentials = _buildCredentials(g);
        const instanceName = (g.name?.toString() ?? "current").replace(
          /[\/\\]/g,
          "_",
        ).replace(/\.\./g, "_").replace(/\0/g, "");
        const content = await context.dataRepository.getContent(
          context.modelType,
          context.modelId,
          instanceName,
        );
        if (!content) {
          throw new Error("No existing state found - run create or get first");
        }
        const existing = JSON.parse(new TextDecoder().decode(content));
        const identifier = existing.GlobalReplicationGroupId?.toString();
        if (!identifier) {
          throw new Error("No identifier found in existing state");
        }
        const currentState = await readResource(
          "AWS::ElastiCache::GlobalReplicationGroup",
          identifier,
          credentials,
        ) as StateData;
        const desiredState: Record<string, unknown> = { ...currentState };
        for (const [key, value] of Object.entries(g)) {
          if (key === "name") continue;
          if (_credentialKeys.has(key)) continue;
          if (value !== undefined) desiredState[key] = value;
        }
        const result = await updateResource(
          "AWS::ElastiCache::GlobalReplicationGroup",
          identifier,
          currentState,
          desiredState,
          undefined,
          credentials,
        );
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    delete: {
      description: "Delete a ElastiCache GlobalReplicationGroup",
      arguments: z.object({
        identifier: z.string().describe(
          "The primary identifier of the ElastiCache GlobalReplicationGroup",
        ),
      }),
      execute: async (args: { identifier: string }, context: any) => {
        const credentials = _buildCredentials(context.globalArgs);
        const { existed } = await deleteResource(
          "AWS::ElastiCache::GlobalReplicationGroup",
          args.identifier,
          credentials,
        );
        const instanceName =
          (context.globalArgs.name?.toString() ?? args.identifier).replace(
            /[\/\\]/g,
            "_",
          ).replace(/\.\./g, "_").replace(/\0/g, "");
        const handle = await context.writeResource("state", instanceName, {
          identifier: args.identifier,
          existed,
          status: existed ? "deleted" : "not_found",
          deletedAt: new Date().toISOString(),
        });
        return { dataHandles: [handle] };
      },
    },
    sync: {
      description: "Sync ElastiCache GlobalReplicationGroup state from AWS",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const credentials = _buildCredentials(g);
        const instanceName = (g.name?.toString() ?? "current").replace(
          /[\/\\]/g,
          "_",
        ).replace(/\.\./g, "_").replace(/\0/g, "");
        const content = await context.dataRepository.getContent(
          context.modelType,
          context.modelId,
          instanceName,
        );
        if (!content) {
          throw new Error("No existing state found - run create or get first");
        }
        const existing = JSON.parse(new TextDecoder().decode(content));
        const identifier = existing.GlobalReplicationGroupId?.toString();
        if (!identifier) {
          throw new Error("No identifier found in existing state");
        }
        try {
          const result = await readResource(
            "AWS::ElastiCache::GlobalReplicationGroup",
            identifier,
            credentials,
          ) as StateData;
          const handle = await context.writeResource(
            "state",
            instanceName,
            result,
          );
          return { dataHandles: [handle] };
        } catch (error: unknown) {
          if (isResourceNotFoundError(error)) {
            const handle = await context.writeResource("state", instanceName, {
              identifier,
              status: "not_found",
              syncedAt: new Date().toISOString(),
            });
            return { dataHandles: [handle] };
          }
          throw error;
        }
      },
    },
  },
};
