// Auto-generated extension model for @swamp/gcp/identitytoolkit/tenants-inboundsamlconfigs
// Do not edit manually. Re-generate with: deno task generate:gcp

// deno-lint-ignore-file no-explicit-any

/**
 * Swamp extension model for Google Cloud Identity Toolkit Tenants.InboundSamlConfigs.
 *
 * A pair of SAML RP-IDP configurations when the project acts as the relying party.
 *
 * Wraps the GCP resource as a swamp model so create, get, update,
 * delete, and sync can be driven through `swamp model`.
 *
 * @module
 */

import { z } from "npm:zod@4.3.6";
import {
  createResource,
  deleteResource,
  getProjectId,
  isResourceNotFoundError,
  listResources,
  readResource,
  updateResource,
} from "./_lib/gcp.ts";

/** Construct the fully-qualified resource name from parent and short name. */
function buildResourceName(parent: string, shortName: string): string {
  return `${parent}/inboundSamlConfigs/${shortName}`;
}

const BASE_URL = "https://identitytoolkit.googleapis.com/";

const GET_CONFIG = {
  "id": "identitytoolkit.projects.tenants.inboundSamlConfigs.get",
  "path": "v2/{+name}",
  "httpMethod": "GET",
  "parameterOrder": [
    "name",
  ],
  "parameters": {
    "name": {
      "location": "path",
      "required": true,
    },
  },
} as const;

const INSERT_CONFIG = {
  "id": "identitytoolkit.projects.tenants.inboundSamlConfigs.create",
  "path": "v2/{+parent}/inboundSamlConfigs",
  "httpMethod": "POST",
  "parameterOrder": [
    "parent",
  ],
  "parameters": {
    "inboundSamlConfigId": {
      "location": "query",
    },
    "parent": {
      "location": "path",
      "required": true,
    },
  },
} as const;

const PATCH_CONFIG = {
  "id": "identitytoolkit.projects.tenants.inboundSamlConfigs.patch",
  "path": "v2/{+name}",
  "httpMethod": "PATCH",
  "parameterOrder": [
    "name",
  ],
  "parameters": {
    "name": {
      "location": "path",
      "required": true,
    },
    "updateMask": {
      "location": "query",
    },
  },
} as const;

const DELETE_CONFIG = {
  "id": "identitytoolkit.projects.tenants.inboundSamlConfigs.delete",
  "path": "v2/{+name}",
  "httpMethod": "DELETE",
  "parameterOrder": [
    "name",
  ],
  "parameters": {
    "name": {
      "location": "path",
      "required": true,
    },
  },
} as const;

const LIST_CONFIG = {
  "id": "identitytoolkit.projects.tenants.inboundSamlConfigs.list",
  "path": "v2/{+parent}/inboundSamlConfigs",
  "httpMethod": "GET",
  "parameterOrder": [
    "parent",
  ],
  "parameters": {
    "pageSize": {
      "location": "query",
    },
    "pageToken": {
      "location": "query",
    },
    "parent": {
      "location": "path",
      "required": true,
    },
  },
} as const;

const GlobalArgsSchema = z.object({
  displayName: z.string().describe(
    "The config's display name set by developers.",
  ).optional(),
  enabled: z.boolean().describe(
    "True if allows the user to sign in with the provider.",
  ).optional(),
  idpConfig: z.object({
    idpCertificates: z.array(z.object({
      x509Certificate: z.string().describe("The x509 certificate").optional(),
    })).describe("IDP's public keys for verifying signature in the assertions.")
      .optional(),
    idpEntityId: z.string().describe("Unique identifier for all SAML entities.")
      .optional(),
    signRequest: z.boolean().describe(
      "Indicates if outbounding SAMLRequest should be signed.",
    ).optional(),
    ssoUrl: z.string().describe("URL to send Authentication request to.")
      .optional(),
  }).describe(
    "The SAML IdP (Identity Provider) configuration when the project acts as the relying party.",
  ).optional(),
  name: z.string().describe(
    "The name of the InboundSamlConfig resource, for example: 'projects/my-awesome-project/inboundSamlConfigs/my-config-id'. Ignored during create requests.",
  ).optional(),
  spConfig: z.object({
    callbackUri: z.string().describe(
      "Callback URI where responses from IDP are handled.",
    ).optional(),
    spCertificates: z.array(z.object({
      expiresAt: z.string().describe(
        "Timestamp of the cert expiration instance.",
      ).optional(),
      x509Certificate: z.string().describe("Self-signed public certificate.")
        .optional(),
    })).describe(
      "Output only. Public certificates generated by the server to verify the signature in SAMLRequest in the SP-initiated flow.",
    ).optional(),
    spEntityId: z.string().describe("Unique identifier for all SAML entities.")
      .optional(),
  }).describe(
    "The SAML SP (Service Provider) configuration when the project acts as the relying party to receive and accept an authentication assertion issued by a SAML identity provider.",
  ).optional(),
  inboundSamlConfigId: z.string().describe("The id to use for this config.")
    .optional(),
  location: z.string().describe(
    "The location for this resource (e.g., 'us', 'us-central1', 'europe-west1')",
  ).optional(),
});

const StateSchema = z.object({
  displayName: z.string().optional(),
  enabled: z.boolean().optional(),
  idpConfig: z.object({
    idpCertificates: z.array(z.object({
      x509Certificate: z.string(),
    })),
    idpEntityId: z.string(),
    signRequest: z.boolean(),
    ssoUrl: z.string(),
  }).optional(),
  name: z.string(),
  spConfig: z.object({
    callbackUri: z.string(),
    spCertificates: z.array(z.object({
      expiresAt: z.string(),
      x509Certificate: z.string(),
    })),
    spEntityId: z.string(),
  }).optional(),
}).passthrough();

type StateData = z.infer<typeof StateSchema>;

const InputsSchema = z.object({
  displayName: z.string().describe(
    "The config's display name set by developers.",
  ).optional(),
  enabled: z.boolean().describe(
    "True if allows the user to sign in with the provider.",
  ).optional(),
  idpConfig: z.object({
    idpCertificates: z.array(z.object({
      x509Certificate: z.string().describe("The x509 certificate").optional(),
    })).describe("IDP's public keys for verifying signature in the assertions.")
      .optional(),
    idpEntityId: z.string().describe("Unique identifier for all SAML entities.")
      .optional(),
    signRequest: z.boolean().describe(
      "Indicates if outbounding SAMLRequest should be signed.",
    ).optional(),
    ssoUrl: z.string().describe("URL to send Authentication request to.")
      .optional(),
  }).describe(
    "The SAML IdP (Identity Provider) configuration when the project acts as the relying party.",
  ).optional(),
  name: z.string().describe(
    "The name of the InboundSamlConfig resource, for example: 'projects/my-awesome-project/inboundSamlConfigs/my-config-id'. Ignored during create requests.",
  ).optional(),
  spConfig: z.object({
    callbackUri: z.string().describe(
      "Callback URI where responses from IDP are handled.",
    ).optional(),
    spCertificates: z.array(z.object({
      expiresAt: z.string().describe(
        "Timestamp of the cert expiration instance.",
      ).optional(),
      x509Certificate: z.string().describe("Self-signed public certificate.")
        .optional(),
    })).describe(
      "Output only. Public certificates generated by the server to verify the signature in SAMLRequest in the SP-initiated flow.",
    ).optional(),
    spEntityId: z.string().describe("Unique identifier for all SAML entities.")
      .optional(),
  }).describe(
    "The SAML SP (Service Provider) configuration when the project acts as the relying party to receive and accept an authentication assertion issued by a SAML identity provider.",
  ).optional(),
  inboundSamlConfigId: z.string().describe("The id to use for this config.")
    .optional(),
  location: z.string().describe(
    "The location for this resource (e.g., 'us', 'us-central1', 'europe-west1')",
  ).optional(),
});

/** Swamp extension model for Google Cloud Identity Toolkit Tenants.InboundSamlConfigs. Registered at `@swamp/gcp/identitytoolkit/tenants-inboundsamlconfigs`. */
export const model = {
  type: "@swamp/gcp/identitytoolkit/tenants-inboundsamlconfigs",
  version: "2026.06.05.1",
  globalArguments: GlobalArgsSchema,
  inputsSchema: InputsSchema,
  resources: {
    state: {
      description:
        "A pair of SAML RP-IDP configurations when the project acts as the relying party.",
      schema: StateSchema,
      lifetime: "infinite",
      garbageCollection: 10,
    },
  },
  methods: {
    create: {
      description: "Create a inboundSamlConfigs",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        params["parent"] = `projects/${projectId}/locations/${
          String(g["location"] ?? "")
        }`;
        const body: Record<string, unknown> = {};
        if (g["displayName"] !== undefined) {
          body["displayName"] = g["displayName"];
        }
        if (g["enabled"] !== undefined) body["enabled"] = g["enabled"];
        if (g["idpConfig"] !== undefined) body["idpConfig"] = g["idpConfig"];
        if (g["name"] !== undefined) body["name"] = g["name"];
        if (g["spConfig"] !== undefined) body["spConfig"] = g["spConfig"];
        if (g["inboundSamlConfigId"] !== undefined) {
          body["inboundSamlConfigId"] = g["inboundSamlConfigId"];
        }
        if (g["name"] !== undefined) {
          params["name"] = buildResourceName(
            `projects/${projectId}/locations/${String(g["location"] ?? "")}`,
            String(g["name"]),
          );
        }
        const result = await createResource(
          BASE_URL,
          INSERT_CONFIG,
          params,
          body,
          GET_CONFIG,
          undefined,
          {
            listConfig: LIST_CONFIG,
            listParams: {
              "parent": `projects/${projectId}/locations/${
                String(g["location"] ?? "")
              }`,
            },
            matchField: "displayName",
            matchValue: String(g["displayName"] ?? ""),
          },
        ) as StateData;
        const instanceName = ((result.name ?? g.name)?.toString() ?? "current")
          .replace(/[\/\\]/g, "_").replace(/\.\./g, "_").replace(/\0/g, "");
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    get: {
      description: "Get a inboundSamlConfigs",
      arguments: z.object({
        identifier: z.string().describe("The name of the inboundSamlConfigs"),
      }),
      execute: async (args: { identifier: string }, context: any) => {
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        const g = context.globalArgs;
        params["name"] = buildResourceName(
          `projects/${projectId}/locations/${String(g["location"] ?? "")}`,
          args.identifier,
        );
        const result = await readResource(
          BASE_URL,
          GET_CONFIG,
          params,
        ) as StateData;
        const instanceName =
          ((result.name ?? g.name)?.toString() ?? args.identifier).replace(
            /[\/\\]/g,
            "_",
          ).replace(/\.\./g, "_").replace(/\0/g, "");
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    update: {
      description: "Update inboundSamlConfigs attributes",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const instanceName = (g.name?.toString() ?? "current").replace(
          /[\/\\]/g,
          "_",
        ).replace(/\.\./g, "_").replace(/\0/g, "");
        const content = await context.dataRepository.getContent(
          context.modelType,
          context.modelId,
          instanceName,
        );
        if (!content) {
          throw new Error("No existing state found - run create or get first");
        }
        const existing = JSON.parse(new TextDecoder().decode(content));
        const params: Record<string, string> = { project: projectId };
        params["name"] = buildResourceName(
          `projects/${projectId}/locations/${String(g["location"] ?? "")}`,
          existing["name"]?.toString() ?? g["name"]?.toString() ?? "",
        );
        const body: Record<string, unknown> = {};
        if (g["displayName"] !== undefined) {
          body["displayName"] = g["displayName"];
        }
        if (g["enabled"] !== undefined) body["enabled"] = g["enabled"];
        if (g["idpConfig"] !== undefined) body["idpConfig"] = g["idpConfig"];
        if (g["spConfig"] !== undefined) body["spConfig"] = g["spConfig"];
        for (const key of Object.keys(existing)) {
          if (
            key === "fingerprint" || key === "labelFingerprint" ||
            key === "etag" || key.endsWith("Fingerprint")
          ) {
            body[key] = existing[key];
          }
        }
        const result = await updateResource(
          BASE_URL,
          PATCH_CONFIG,
          params,
          body,
          GET_CONFIG,
        ) as StateData;
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    delete: {
      description: "Delete the inboundSamlConfigs",
      arguments: z.object({
        identifier: z.string().describe("The name of the inboundSamlConfigs"),
      }),
      execute: async (args: { identifier: string }, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        params["name"] = buildResourceName(
          `projects/${projectId}/locations/${String(g["location"] ?? "")}`,
          args.identifier,
        );
        const { existed } = await deleteResource(
          BASE_URL,
          DELETE_CONFIG,
          params,
        );
        const instanceName = (g.name?.toString() ?? args.identifier).replace(
          /[\/\\]/g,
          "_",
        ).replace(/\.\./g, "_").replace(/\0/g, "");
        const handle = await context.writeResource("state", instanceName, {
          identifier: args.identifier,
          existed,
          status: existed ? "deleted" : "not_found",
          deletedAt: new Date().toISOString(),
        });
        return { dataHandles: [handle] };
      },
    },
    sync: {
      description: "Sync inboundSamlConfigs state from GCP",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const instanceName = (g.name?.toString() ?? "current").replace(
          /[\/\\]/g,
          "_",
        ).replace(/\.\./g, "_").replace(/\0/g, "");
        const content = await context.dataRepository.getContent(
          context.modelType,
          context.modelId,
          instanceName,
        );
        if (!content) {
          throw new Error("No existing state found - run create or get first");
        }
        const existing = JSON.parse(new TextDecoder().decode(content));
        try {
          const params: Record<string, string> = { project: projectId };
          const shortName = existing.name?.toString() ?? g["name"]?.toString();
          if (!shortName) throw new Error("No identifier found");
          params["name"] = buildResourceName(
            `projects/${projectId}/locations/${String(g["location"] ?? "")}`,
            shortName,
          );
          const result = await readResource(
            BASE_URL,
            GET_CONFIG,
            params,
          ) as StateData;
          const handle = await context.writeResource(
            "state",
            instanceName,
            result,
          );
          return { dataHandles: [handle] };
        } catch (error: unknown) {
          if (isResourceNotFoundError(error)) {
            const handle = await context.writeResource("state", instanceName, {
              status: "not_found",
              syncedAt: new Date().toISOString(),
            });
            return { dataHandles: [handle] };
          }
          throw error;
        }
      },
    },
    list: {
      description: "List inboundSamlConfigs resources",
      arguments: z.object({
        pageSize: z.number().describe("The maximum number of items to return.")
          .optional(),
        maxPages: z.number().describe(
          "Maximum number of pages to fetch (default: 10)",
        ).optional(),
      }),
      execute: async (args: Record<string, unknown>, context: any) => {
        const g = context.globalArgs;
        const projectId = await getProjectId();
        const params: Record<string, string> = { project: projectId };
        params["parent"] = `projects/${projectId}/locations/${
          String(g["location"] ?? "")
        }`;
        if (args["pageSize"] !== undefined) {
          params["pageSize"] = String(args["pageSize"]);
        }
        const { items, nextPageToken } = await listResources(
          BASE_URL,
          LIST_CONFIG,
          params,
          "inboundSamlConfigs",
          (args.maxPages as number | undefined) ?? 10,
        );
        const dataHandles = [];
        for (let i = 0; i < items.length; i++) {
          const item = items[i] as StateData;
          const instanceName = (item.name?.toString() ?? String(i)).replace(
            /[\/\\]/g,
            "_",
          ).replace(/\.\./g, "_").replace(/\0/g, "");
          const handle = await context.writeResource(
            "state",
            instanceName,
            item,
          );
          dataHandles.push(handle);
        }
        return { dataHandles, result: { count: items.length, nextPageToken } };
      },
    },
  },
};
