// Auto-generated extension model for @swamp/gcp/aiplatform/reasoningengines-memories
// Do not edit manually. Re-generate with: deno task generate:gcp

// deno-lint-ignore-file no-explicit-any

/**
 * Swamp extension model for Google Cloud Agent Platform ReasoningEngines.Memories.
 *
 * A memory.
 *
 * Wraps the GCP resource as a swamp model so create, get, update,
 * delete, and sync can be driven through `swamp model`.
 *
 * @module
 */

import { z } from "npm:zod@4.3.6";
import {
  createResource,
  deleteResource,
  type ExplicitGcpCredentials,
  getProjectId,
  isResourceNotFoundError,
  listResources,
  readResource,
  updateResource,
} from "./_lib/gcp.ts";

/** Construct the fully-qualified resource name from parent and short name. */
function buildResourceName(parent: string, shortName: string): string {
  return `${parent}/memories/${shortName}`;
}

const BASE_URL = "https://aiplatform.googleapis.com/";

const GET_CONFIG = {
  "id": "aiplatform.projects.locations.reasoningEngines.memories.get",
  "path": "v1/{+name}",
  "httpMethod": "GET",
  "parameterOrder": [
    "name",
  ],
  "parameters": {
    "name": {
      "location": "path",
      "required": true,
    },
  },
} as const;

const INSERT_CONFIG = {
  "id": "aiplatform.projects.locations.reasoningEngines.memories.create",
  "path": "v1/{+parent}/memories",
  "httpMethod": "POST",
  "parameterOrder": [
    "parent",
  ],
  "parameters": {
    "memoryId": {
      "location": "query",
    },
    "parent": {
      "location": "path",
      "required": true,
    },
  },
} as const;

const PATCH_CONFIG = {
  "id": "aiplatform.projects.locations.reasoningEngines.memories.patch",
  "path": "v1/{+name}",
  "httpMethod": "PATCH",
  "parameterOrder": [
    "name",
  ],
  "parameters": {
    "name": {
      "location": "path",
      "required": true,
    },
    "updateMask": {
      "location": "query",
    },
  },
} as const;

const DELETE_CONFIG = {
  "id": "aiplatform.projects.locations.reasoningEngines.memories.delete",
  "path": "v1/{+name}",
  "httpMethod": "DELETE",
  "parameterOrder": [
    "name",
  ],
  "parameters": {
    "name": {
      "location": "path",
      "required": true,
    },
  },
} as const;

const LIST_CONFIG = {
  "id": "aiplatform.projects.locations.reasoningEngines.memories.list",
  "path": "v1/{+parent}/memories",
  "httpMethod": "GET",
  "parameterOrder": [
    "parent",
  ],
  "parameters": {
    "filter": {
      "location": "query",
    },
    "orderBy": {
      "location": "query",
    },
    "pageSize": {
      "location": "query",
    },
    "pageToken": {
      "location": "query",
    },
    "parent": {
      "location": "path",
      "required": true,
    },
  },
} as const;

const GlobalArgsSchema = z.object({
  accessToken: z.string().meta({ sensitive: true }).describe(
    "GCP OAuth2 access token; overrides GCP_ACCESS_TOKEN environment variable. Wire with a vault.get(...) expression to source it from a vault.",
  ).optional(),
  credentialsJson: z.string().meta({ sensitive: true }).describe(
    "GCP service account JSON credentials; overrides GOOGLE_APPLICATION_CREDENTIALS_JSON environment variable. Wire with a vault.get(...) expression to source it from a vault.",
  ).optional(),
  project: z.string().describe(
    "GCP project ID; overrides GCP_PROJECT / GOOGLE_CLOUD_PROJECT environment variables.",
  ).optional(),
  description: z.string().describe(
    "Optional. Represents the description of the Memory.",
  ).optional(),
  disableMemoryRevisions: z.boolean().describe(
    "Optional. Input only. Indicates whether no revision will be created for this request.",
  ).optional(),
  displayName: z.string().describe(
    "Optional. Represents the display name of the Memory.",
  ).optional(),
  expireTime: z.string().describe(
    "Optional. Represents the timestamp of when this resource is considered expired. This is *always* provided on output when `expiration` is set on input, regardless of whether `expire_time` or `ttl` was provided.",
  ).optional(),
  fact: z.string().describe(
    "Optional. Represents semantic knowledge extracted from the source content.",
  ).optional(),
  metadata: z.record(
    z.string(),
    z.object({
      boolValue: z.boolean().describe("Represents a boolean value.").optional(),
      doubleValue: z.number().describe("Represents a double value.").optional(),
      stringValue: z.string().describe("Represents a string value.").optional(),
      timestampValue: z.string().describe(
        "Represents a timestamp value. When filtering on timestamp values, only the seconds field will be compared.",
      ).optional(),
    }),
  ).describe(
    "Optional. Represents user-provided metadata for the Memory. This information was provided when creating, updating, or generating the Memory. It was not generated by Memory Bank.",
  ).optional(),
  name: z.string().describe(
    "Identifier. Represents the resource name of the Memory. Format: `projects/{project}/locations/{location}/reasoningEngines/{reasoning_engine}/memories/{memory}`",
  ).optional(),
  revisionExpireTime: z.string().describe(
    "Optional. Input only. Represents the timestamp of when the revision is considered expired. If not set, the memory revision will be kept until manually deleted.",
  ).optional(),
  revisionLabels: z.record(z.string(), z.string()).describe(
    "Optional. Input only. Represents the labels to apply to the Memory Revision created as a result of this request.",
  ).optional(),
  revisionTtl: z.string().describe(
    "Optional. Input only. Represents the TTL for the revision. The expiration time is computed: now + TTL.",
  ).optional(),
  scope: z.record(z.string(), z.string()).describe(
    "Required. Immutable. Represents the scope of the Memory. Memories are isolated within their scope. The scope is defined when creating or generating memories. Scope values cannot contain the wildcard character '*'.",
  ).optional(),
  topics: z.array(z.object({
    customMemoryTopicLabel: z.string().describe(
      "Optional. Represents the custom memory topic label.",
    ).optional(),
    managedMemoryTopic: z.enum([
      "MANAGED_TOPIC_ENUM_UNSPECIFIED",
      "USER_PERSONAL_INFO",
      "USER_PREFERENCES",
      "KEY_CONVERSATION_DETAILS",
      "EXPLICIT_INSTRUCTIONS",
    ]).describe("Optional. Represents the managed memory topic.").optional(),
  })).describe("Optional. Represents the Topics of the Memory.").optional(),
  ttl: z.string().describe(
    "Optional. Input only. Represents the TTL for this resource. The expiration time is computed: now + TTL.",
  ).optional(),
  memoryId: z.string().describe(
    "Optional. The user defined ID to use for memory, which will become the final component of the memory resource name. If not provided, Vertex AI will generate a value for this ID. This value may be up to 63 characters, and valid characters are `[a-z0-9-]`. The first character must be a letter, and the last character must be a letter or number.",
  ).optional(),
  location: z.string().describe(
    "The location for this resource (e.g., 'us', 'us-central1', 'europe-west1')",
  ).optional(),
});

const StateSchema = z.object({
  createTime: z.string().optional(),
  description: z.string().optional(),
  disableMemoryRevisions: z.boolean().optional(),
  displayName: z.string().optional(),
  expireTime: z.string().optional(),
  fact: z.string().optional(),
  metadata: z.record(z.string(), z.unknown()).optional(),
  name: z.string(),
  revisionExpireTime: z.string().optional(),
  revisionLabels: z.record(z.string(), z.unknown()).optional(),
  revisionTtl: z.string().optional(),
  scope: z.record(z.string(), z.unknown()).optional(),
  topics: z.array(z.object({
    customMemoryTopicLabel: z.string(),
    managedMemoryTopic: z.string(),
  })).optional(),
  ttl: z.string().optional(),
  updateTime: z.string().optional(),
}).passthrough();

type StateData = z.infer<typeof StateSchema>;

const InputsSchema = z.object({
  accessToken: z.string().meta({ sensitive: true }).optional(),
  credentialsJson: z.string().meta({ sensitive: true }).optional(),
  project: z.string().optional(),
  description: z.string().describe(
    "Optional. Represents the description of the Memory.",
  ).optional(),
  disableMemoryRevisions: z.boolean().describe(
    "Optional. Input only. Indicates whether no revision will be created for this request.",
  ).optional(),
  displayName: z.string().describe(
    "Optional. Represents the display name of the Memory.",
  ).optional(),
  expireTime: z.string().describe(
    "Optional. Represents the timestamp of when this resource is considered expired. This is *always* provided on output when `expiration` is set on input, regardless of whether `expire_time` or `ttl` was provided.",
  ).optional(),
  fact: z.string().describe(
    "Optional. Represents semantic knowledge extracted from the source content.",
  ).optional(),
  metadata: z.record(
    z.string(),
    z.object({
      boolValue: z.boolean().describe("Represents a boolean value.").optional(),
      doubleValue: z.number().describe("Represents a double value.").optional(),
      stringValue: z.string().describe("Represents a string value.").optional(),
      timestampValue: z.string().describe(
        "Represents a timestamp value. When filtering on timestamp values, only the seconds field will be compared.",
      ).optional(),
    }),
  ).describe(
    "Optional. Represents user-provided metadata for the Memory. This information was provided when creating, updating, or generating the Memory. It was not generated by Memory Bank.",
  ).optional(),
  name: z.string().describe(
    "Identifier. Represents the resource name of the Memory. Format: `projects/{project}/locations/{location}/reasoningEngines/{reasoning_engine}/memories/{memory}`",
  ).optional(),
  revisionExpireTime: z.string().describe(
    "Optional. Input only. Represents the timestamp of when the revision is considered expired. If not set, the memory revision will be kept until manually deleted.",
  ).optional(),
  revisionLabels: z.record(z.string(), z.string()).describe(
    "Optional. Input only. Represents the labels to apply to the Memory Revision created as a result of this request.",
  ).optional(),
  revisionTtl: z.string().describe(
    "Optional. Input only. Represents the TTL for the revision. The expiration time is computed: now + TTL.",
  ).optional(),
  scope: z.record(z.string(), z.string()).describe(
    "Required. Immutable. Represents the scope of the Memory. Memories are isolated within their scope. The scope is defined when creating or generating memories. Scope values cannot contain the wildcard character '*'.",
  ).optional(),
  topics: z.array(z.object({
    customMemoryTopicLabel: z.string().describe(
      "Optional. Represents the custom memory topic label.",
    ).optional(),
    managedMemoryTopic: z.enum([
      "MANAGED_TOPIC_ENUM_UNSPECIFIED",
      "USER_PERSONAL_INFO",
      "USER_PREFERENCES",
      "KEY_CONVERSATION_DETAILS",
      "EXPLICIT_INSTRUCTIONS",
    ]).describe("Optional. Represents the managed memory topic.").optional(),
  })).describe("Optional. Represents the Topics of the Memory.").optional(),
  ttl: z.string().describe(
    "Optional. Input only. Represents the TTL for this resource. The expiration time is computed: now + TTL.",
  ).optional(),
  memoryId: z.string().describe(
    "Optional. The user defined ID to use for memory, which will become the final component of the memory resource name. If not provided, Vertex AI will generate a value for this ID. This value may be up to 63 characters, and valid characters are `[a-z0-9-]`. The first character must be a letter, and the last character must be a letter or number.",
  ).optional(),
  location: z.string().describe(
    "The location for this resource (e.g., 'us', 'us-central1', 'europe-west1')",
  ).optional(),
});

const _credentialKeys = new Set(["accessToken", "credentialsJson", "project"]);

function _buildGcpCredentials(
  g: Record<string, unknown>,
): ExplicitGcpCredentials {
  return {
    accessToken: g.accessToken as string | undefined,
    credentialsJson: g.credentialsJson as string | undefined,
    project: g.project as string | undefined,
  };
}

/** Swamp extension model for Google Cloud Agent Platform ReasoningEngines.Memories. Registered at `@swamp/gcp/aiplatform/reasoningengines-memories`. */
export const model = {
  type: "@swamp/gcp/aiplatform/reasoningengines-memories",
  version: "2026.06.07.1",
  upgrades: [
    {
      toVersion: "2026.04.01.1",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.04.02.2",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.04.03.1",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.04.03.2",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.04.03.3",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.04.05.1",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.04.11.1",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.04.23.1",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.05.02.1",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.05.18.1",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.05.18.2",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.05.19.1",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.05.19.2",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.05.20.1",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.05.21.1",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.05.21.2",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.05.24.1",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.05.25.1",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.05.26.1",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.06.07.1",
      description: "Added: accessToken, credentialsJson, project",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
  ],
  globalArguments: GlobalArgsSchema,
  inputsSchema: InputsSchema,
  resources: {
    state: {
      description: "A memory.",
      schema: StateSchema,
      lifetime: "infinite",
      garbageCollection: 10,
    },
  },
  methods: {
    create: {
      description: "Create a memories",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const credentials = _buildGcpCredentials(g);
        const projectId = await getProjectId(credentials);
        const params: Record<string, string> = { project: projectId };
        params["parent"] = `projects/${projectId}/locations/${
          String(g["location"] ?? "")
        }`;
        const body: Record<string, unknown> = {};
        if (g["description"] !== undefined) {
          body["description"] = g["description"];
        }
        if (g["disableMemoryRevisions"] !== undefined) {
          body["disableMemoryRevisions"] = g["disableMemoryRevisions"];
        }
        if (g["displayName"] !== undefined) {
          body["displayName"] = g["displayName"];
        }
        if (g["expireTime"] !== undefined) body["expireTime"] = g["expireTime"];
        if (g["fact"] !== undefined) body["fact"] = g["fact"];
        if (g["metadata"] !== undefined) body["metadata"] = g["metadata"];
        if (g["name"] !== undefined) body["name"] = g["name"];
        if (g["revisionExpireTime"] !== undefined) {
          body["revisionExpireTime"] = g["revisionExpireTime"];
        }
        if (g["revisionLabels"] !== undefined) {
          body["revisionLabels"] = g["revisionLabels"];
        }
        if (g["revisionTtl"] !== undefined) {
          body["revisionTtl"] = g["revisionTtl"];
        }
        if (g["scope"] !== undefined) body["scope"] = g["scope"];
        if (g["topics"] !== undefined) body["topics"] = g["topics"];
        if (g["ttl"] !== undefined) body["ttl"] = g["ttl"];
        if (g["memoryId"] !== undefined) body["memoryId"] = g["memoryId"];
        if (g["name"] !== undefined) {
          params["name"] = buildResourceName(
            `projects/${projectId}/locations/${String(g["location"] ?? "")}`,
            String(g["name"]),
          );
        }
        const result = await createResource(
          BASE_URL,
          INSERT_CONFIG,
          params,
          body,
          GET_CONFIG,
          undefined,
          {
            listConfig: LIST_CONFIG,
            listParams: {
              "parent": `projects/${projectId}/locations/${
                String(g["location"] ?? "")
              }`,
            },
            matchField: "displayName",
            matchValue: String(g["displayName"] ?? ""),
          },
          credentials,
        ) as StateData;
        const instanceName = ((result.name ?? g.name)?.toString() ?? "current")
          .replace(/[\/\\]/g, "_").replace(/\.\./g, "_").replace(/\0/g, "");
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    get: {
      description: "Get a memories",
      arguments: z.object({
        identifier: z.string().describe("The name of the memories"),
      }),
      execute: async (args: { identifier: string }, context: any) => {
        const g = context.globalArgs;
        const credentials = _buildGcpCredentials(g);
        const projectId = await getProjectId(credentials);
        const params: Record<string, string> = { project: projectId };
        params["name"] = buildResourceName(
          `projects/${projectId}/locations/${String(g["location"] ?? "")}`,
          args.identifier,
        );
        const result = await readResource(
          BASE_URL,
          GET_CONFIG,
          params,
          credentials,
        ) as StateData;
        const instanceName =
          ((result.name ?? g.name)?.toString() ?? args.identifier).replace(
            /[\/\\]/g,
            "_",
          ).replace(/\.\./g, "_").replace(/\0/g, "");
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    update: {
      description: "Update memories attributes",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const credentials = _buildGcpCredentials(g);
        const projectId = await getProjectId(credentials);
        const instanceName = (g.name?.toString() ?? "current").replace(
          /[\/\\]/g,
          "_",
        ).replace(/\.\./g, "_").replace(/\0/g, "");
        const content = await context.dataRepository.getContent(
          context.modelType,
          context.modelId,
          instanceName,
        );
        if (!content) {
          throw new Error("No existing state found - run create or get first");
        }
        const existing = JSON.parse(new TextDecoder().decode(content));
        const params: Record<string, string> = { project: projectId };
        params["name"] = buildResourceName(
          `projects/${projectId}/locations/${String(g["location"] ?? "")}`,
          existing["name"]?.toString() ?? g["name"]?.toString() ?? "",
        );
        const body: Record<string, unknown> = {};
        if (g["description"] !== undefined) {
          body["description"] = g["description"];
        }
        if (g["disableMemoryRevisions"] !== undefined) {
          body["disableMemoryRevisions"] = g["disableMemoryRevisions"];
        }
        if (g["displayName"] !== undefined) {
          body["displayName"] = g["displayName"];
        }
        if (g["expireTime"] !== undefined) body["expireTime"] = g["expireTime"];
        if (g["fact"] !== undefined) body["fact"] = g["fact"];
        if (g["metadata"] !== undefined) body["metadata"] = g["metadata"];
        if (g["revisionExpireTime"] !== undefined) {
          body["revisionExpireTime"] = g["revisionExpireTime"];
        }
        if (g["revisionLabels"] !== undefined) {
          body["revisionLabels"] = g["revisionLabels"];
        }
        if (g["revisionTtl"] !== undefined) {
          body["revisionTtl"] = g["revisionTtl"];
        }
        if (g["topics"] !== undefined) body["topics"] = g["topics"];
        if (g["ttl"] !== undefined) body["ttl"] = g["ttl"];
        for (const key of Object.keys(existing)) {
          if (
            key === "fingerprint" || key === "labelFingerprint" ||
            key === "etag" || key.endsWith("Fingerprint")
          ) {
            body[key] = existing[key];
          }
        }
        const result = await updateResource(
          BASE_URL,
          PATCH_CONFIG,
          params,
          body,
          GET_CONFIG,
          undefined,
          credentials,
        ) as StateData;
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    delete: {
      description: "Delete the memories",
      arguments: z.object({
        identifier: z.string().describe("The name of the memories"),
      }),
      execute: async (args: { identifier: string }, context: any) => {
        const g = context.globalArgs;
        const credentials = _buildGcpCredentials(g);
        const projectId = await getProjectId(credentials);
        const params: Record<string, string> = { project: projectId };
        params["name"] = buildResourceName(
          `projects/${projectId}/locations/${String(g["location"] ?? "")}`,
          args.identifier,
        );
        const { existed } = await deleteResource(
          BASE_URL,
          DELETE_CONFIG,
          params,
          credentials,
        );
        const instanceName = (g.name?.toString() ?? args.identifier).replace(
          /[\/\\]/g,
          "_",
        ).replace(/\.\./g, "_").replace(/\0/g, "");
        const handle = await context.writeResource("state", instanceName, {
          identifier: args.identifier,
          existed,
          status: existed ? "deleted" : "not_found",
          deletedAt: new Date().toISOString(),
        });
        return { dataHandles: [handle] };
      },
    },
    sync: {
      description: "Sync memories state from GCP",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const credentials = _buildGcpCredentials(g);
        const projectId = await getProjectId(credentials);
        const instanceName = (g.name?.toString() ?? "current").replace(
          /[\/\\]/g,
          "_",
        ).replace(/\.\./g, "_").replace(/\0/g, "");
        const content = await context.dataRepository.getContent(
          context.modelType,
          context.modelId,
          instanceName,
        );
        if (!content) {
          throw new Error("No existing state found - run create or get first");
        }
        const existing = JSON.parse(new TextDecoder().decode(content));
        try {
          const params: Record<string, string> = { project: projectId };
          const shortName = existing.name?.toString() ?? g["name"]?.toString();
          if (!shortName) throw new Error("No identifier found");
          params["name"] = buildResourceName(
            `projects/${projectId}/locations/${String(g["location"] ?? "")}`,
            shortName,
          );
          const result = await readResource(
            BASE_URL,
            GET_CONFIG,
            params,
            credentials,
          ) as StateData;
          const handle = await context.writeResource(
            "state",
            instanceName,
            result,
          );
          return { dataHandles: [handle] };
        } catch (error: unknown) {
          if (isResourceNotFoundError(error)) {
            const handle = await context.writeResource("state", instanceName, {
              status: "not_found",
              syncedAt: new Date().toISOString(),
            });
            return { dataHandles: [handle] };
          }
          throw error;
        }
      },
    },
    list: {
      description: "List memories resources",
      arguments: z.object({
        filter: z.string().describe(
          'Optional. The standard list filter. More detail in [AIP-160](https://google.aip.dev/160). Supported fields: * `scope` (as a JSON string with equality match only) * `topics` (i.e. `topics.custom_memory_topic_label: "example topic" OR topics.managed_memory_topic: USER_PREFERENCES`)',
        ).optional(),
        orderBy: z.string().describe(
          "Optional. The standard list order by string. If not specified, the default order is `create_time desc`. If specified, the default sorting order of provided fields is ascending. More detail in [AIP-132](https://google.aip.dev/132). Supported fields: * `create_time` * `update_time`",
        ).optional(),
        pageSize: z.number().describe("Optional. The standard list page size.")
          .optional(),
        maxPages: z.number().describe(
          "Maximum number of pages to fetch (default: 10)",
        ).optional(),
      }),
      execute: async (args: Record<string, unknown>, context: any) => {
        const g = context.globalArgs;
        const credentials = _buildGcpCredentials(g);
        const projectId = await getProjectId(credentials);
        const params: Record<string, string> = { project: projectId };
        params["parent"] = `projects/${projectId}/locations/${
          String(g["location"] ?? "")
        }`;
        if (args["filter"] !== undefined) {
          params["filter"] = String(args["filter"]);
        }
        if (args["orderBy"] !== undefined) {
          params["orderBy"] = String(args["orderBy"]);
        }
        if (args["pageSize"] !== undefined) {
          params["pageSize"] = String(args["pageSize"]);
        }
        const { items, nextPageToken } = await listResources(
          BASE_URL,
          LIST_CONFIG,
          params,
          "memories",
          (args.maxPages as number | undefined) ?? 10,
          credentials,
        );
        const dataHandles = [];
        for (let i = 0; i < items.length; i++) {
          const item = items[i] as StateData;
          const instanceName = (item.name?.toString() ?? String(i)).replace(
            /[\/\\]/g,
            "_",
          ).replace(/\.\./g, "_").replace(/\0/g, "");
          const handle = await context.writeResource(
            "state",
            instanceName,
            item,
          );
          dataHandles.push(handle);
        }
        return { dataHandles, result: { count: items.length, nextPageToken } };
      },
    },
    generate: {
      description: "generate",
      arguments: z.object({
        allowedTopics: z.any().optional(),
        directContentsSource: z.any().optional(),
        directMemoriesSource: z.any().optional(),
        disableConsolidation: z.any().optional(),
        disableMemoryRevisions: z.any().optional(),
        metadata: z.any().optional(),
        metadataMergeStrategy: z.any().optional(),
        revisionExpireTime: z.any().optional(),
        revisionLabels: z.any().optional(),
        revisionTtl: z.any().optional(),
        scope: z.any().optional(),
        vertexSessionSource: z.any().optional(),
      }),
      execute: async (args: Record<string, unknown>, context: any) => {
        const g = context.globalArgs;
        const credentials = _buildGcpCredentials(g);
        const projectId = await getProjectId(credentials);
        const params: Record<string, string> = { project: projectId };
        params["parent"] = `projects/${projectId}/locations/${
          String(g["location"] ?? "")
        }`;
        const body: Record<string, unknown> = {};
        if (args["allowedTopics"] !== undefined) {
          body["allowedTopics"] = args["allowedTopics"];
        }
        if (args["directContentsSource"] !== undefined) {
          body["directContentsSource"] = args["directContentsSource"];
        }
        if (args["directMemoriesSource"] !== undefined) {
          body["directMemoriesSource"] = args["directMemoriesSource"];
        }
        if (args["disableConsolidation"] !== undefined) {
          body["disableConsolidation"] = args["disableConsolidation"];
        }
        if (args["disableMemoryRevisions"] !== undefined) {
          body["disableMemoryRevisions"] = args["disableMemoryRevisions"];
        }
        if (args["metadata"] !== undefined) body["metadata"] = args["metadata"];
        if (args["metadataMergeStrategy"] !== undefined) {
          body["metadataMergeStrategy"] = args["metadataMergeStrategy"];
        }
        if (args["revisionExpireTime"] !== undefined) {
          body["revisionExpireTime"] = args["revisionExpireTime"];
        }
        if (args["revisionLabels"] !== undefined) {
          body["revisionLabels"] = args["revisionLabels"];
        }
        if (args["revisionTtl"] !== undefined) {
          body["revisionTtl"] = args["revisionTtl"];
        }
        if (args["scope"] !== undefined) body["scope"] = args["scope"];
        if (args["vertexSessionSource"] !== undefined) {
          body["vertexSessionSource"] = args["vertexSessionSource"];
        }
        const result = await createResource(
          BASE_URL,
          {
            "id":
              "aiplatform.projects.locations.reasoningEngines.memories.generate",
            "path": "v1/{+parent}/memories:generate",
            "httpMethod": "POST",
            "parameterOrder": ["parent"],
            "parameters": {
              "parent": { "location": "path", "required": true },
            },
          },
          params,
          body,
          undefined,
          undefined,
          undefined,
          credentials,
        );
        return { result };
      },
    },
    purge: {
      description: "purge",
      arguments: z.object({
        filter: z.any().optional(),
        filterGroups: z.any().optional(),
        force: z.any().optional(),
      }),
      execute: async (args: Record<string, unknown>, context: any) => {
        const g = context.globalArgs;
        const credentials = _buildGcpCredentials(g);
        const projectId = await getProjectId(credentials);
        const params: Record<string, string> = { project: projectId };
        params["parent"] = `projects/${projectId}/locations/${
          String(g["location"] ?? "")
        }`;
        const body: Record<string, unknown> = {};
        if (args["filter"] !== undefined) body["filter"] = args["filter"];
        if (args["filterGroups"] !== undefined) {
          body["filterGroups"] = args["filterGroups"];
        }
        if (args["force"] !== undefined) body["force"] = args["force"];
        const result = await createResource(
          BASE_URL,
          {
            "id":
              "aiplatform.projects.locations.reasoningEngines.memories.purge",
            "path": "v1/{+parent}/memories:purge",
            "httpMethod": "POST",
            "parameterOrder": ["parent"],
            "parameters": {
              "parent": { "location": "path", "required": true },
            },
          },
          params,
          body,
          undefined,
          undefined,
          undefined,
          credentials,
        );
        return { result };
      },
    },
    retrieve: {
      description: "retrieve",
      arguments: z.object({
        filter: z.any().optional(),
        filterGroups: z.any().optional(),
        memoryTypes: z.any().optional(),
        scope: z.any().optional(),
        similaritySearchParams: z.any().optional(),
        simpleRetrievalParams: z.any().optional(),
      }),
      execute: async (args: Record<string, unknown>, context: any) => {
        const g = context.globalArgs;
        const credentials = _buildGcpCredentials(g);
        const projectId = await getProjectId(credentials);
        const params: Record<string, string> = { project: projectId };
        params["parent"] = `projects/${projectId}/locations/${
          String(g["location"] ?? "")
        }`;
        const body: Record<string, unknown> = {};
        if (args["filter"] !== undefined) body["filter"] = args["filter"];
        if (args["filterGroups"] !== undefined) {
          body["filterGroups"] = args["filterGroups"];
        }
        if (args["memoryTypes"] !== undefined) {
          body["memoryTypes"] = args["memoryTypes"];
        }
        if (args["scope"] !== undefined) body["scope"] = args["scope"];
        if (args["similaritySearchParams"] !== undefined) {
          body["similaritySearchParams"] = args["similaritySearchParams"];
        }
        if (args["simpleRetrievalParams"] !== undefined) {
          body["simpleRetrievalParams"] = args["simpleRetrievalParams"];
        }
        const result = await createResource(
          BASE_URL,
          {
            "id":
              "aiplatform.projects.locations.reasoningEngines.memories.retrieve",
            "path": "v1/{+parent}/memories:retrieve",
            "httpMethod": "POST",
            "parameterOrder": ["parent"],
            "parameters": {
              "parent": { "location": "path", "required": true },
            },
          },
          params,
          body,
          undefined,
          undefined,
          undefined,
          credentials,
        );
        return { result };
      },
    },
    rollback: {
      description: "rollback",
      arguments: z.object({
        targetRevisionId: z.any().optional(),
      }),
      execute: async (args: Record<string, unknown>, context: any) => {
        const g = context.globalArgs;
        const credentials = _buildGcpCredentials(g);
        const projectId = await getProjectId(credentials);
        const params: Record<string, string> = { project: projectId };
        if (g["name"] !== undefined) {
          params["name"] = buildResourceName(
            `projects/${projectId}/locations/${String(g["location"] ?? "")}`,
            String(g["name"]),
          );
        }
        const body: Record<string, unknown> = {};
        if (args["targetRevisionId"] !== undefined) {
          body["targetRevisionId"] = args["targetRevisionId"];
        }
        const result = await createResource(
          BASE_URL,
          {
            "id":
              "aiplatform.projects.locations.reasoningEngines.memories.rollback",
            "path": "v1/{+name}:rollback",
            "httpMethod": "POST",
            "parameterOrder": ["name"],
            "parameters": { "name": { "location": "path", "required": true } },
          },
          params,
          body,
          undefined,
          undefined,
          undefined,
          credentials,
        );
        return { result };
      },
    },
  },
};
