// Swamp, an Automation Framework Copyright (C) 2026 System Initiative, Inc.
//
// This file is part of Swamp.
//
// Swamp is free software: you can redistribute it and/or modify it under the terms
// of the GNU Affero General Public License version 3 as published by the Free
// Software Foundation, with the Swamp Extension and Definition Exception (found in
// the "COPYING-EXCEPTION" file).
//
// Swamp is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
// PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License along
// with Swamp. If not, see <https://www.gnu.org/licenses/>.

// Embeds the skill's example factory definitions in the engine as the
// starters a factory's init method copies (swamp-club #2803).
//
// They cannot be read beside the model at run time: swamp bundles a model
// before importing it, so import.meta.url points into .swamp/, and
// context.extensionFile() needs a manifest, which gatorwalk-factory has none
// of until go-live. So the text is generated into a module the bundle
// carries, and gen_starters_test fails when it drifts from the examples.
//
//   deno task gen:starters   # rewrite starters.ts, then format it

const ROOT = new URL("../", import.meta.url);
export const EXAMPLES_DIR = new URL(
  ".claude/skills/gatorwalk-factory/references/examples/",
  ROOT,
);
export const STARTERS_FILE = new URL(
  "extensions/models/_lib/engine/starters.ts",
  ROOT,
);

const HEADER =
  `// Swamp, an Automation Framework Copyright (C) 2026 System Initiative, Inc.
//
// This file is part of Swamp.
//
// Swamp is free software: you can redistribute it and/or modify it under the terms
// of the GNU Affero General Public License version 3 as published by the Free
// Software Foundation, with the Swamp Extension and Definition Exception (found in
// the "COPYING-EXCEPTION" file).
//
// Swamp is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
// PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License along
// with Swamp. If not, see <https://www.gnu.org/licenses/>.

// Generated by scripts/gen_starters.ts from the skill's examples
// (.claude/skills/gatorwalk-factory/references/examples/). Do not edit: change
// an example, then run deno task gen:starters.
`;

/** The examples by name (the file's basename), in name order. */
export async function readExamples(): Promise<Map<string, string>> {
  const names: string[] = [];
  for await (const entry of Deno.readDir(EXAMPLES_DIR)) {
    if (entry.isFile && entry.name.endsWith(".yaml")) names.push(entry.name);
  }
  names.sort();
  const examples = new Map<string, string>();
  for (const file of names) {
    examples.set(
      file.slice(0, -".yaml".length),
      await Deno.readTextFile(new URL(file, EXAMPLES_DIR)),
    );
  }
  return examples;
}

/** The starters module's text for the given examples. */
export function renderStarters(examples: Map<string, string>): string {
  const entries = [...examples].map(([name, text]) =>
    `  ${JSON.stringify(name)}:\n    ${JSON.stringify(text)},\n`
  ).join("");
  return `${HEADER}
/** Starter factory definitions by name, as YAML text. */
export const STARTERS: Readonly<Record<string, string>> = {
${entries}};
`;
}

if (import.meta.main) {
  await Deno.writeTextFile(
    STARTERS_FILE,
    renderStarters(await readExamples()),
  );
  console.log(`wrote ${STARTERS_FILE.pathname}`);
}
