// Swamp, an Automation Framework
// Copyright (C) 2026 Elder Swamp Club, Inc.
//
// This file is part of Swamp.
//
// Swamp is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License version 3
// as published by the Free Software Foundation, with the Swamp
// Extension and Definition Exception (found in the "COPYING-EXCEPTION"
// file).
//
// Swamp is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with Swamp.  If not, see <https://www.gnu.org/licenses/>.

// Auto-generated extension model for @swamp/gcp/cloudbuild/builds
// Do not edit manually. Re-generate with: deno task generate:gcp

// deno-lint-ignore-file no-explicit-any

/**
 * Swamp extension model for Google Cloud Build Builds.
 *
 * A build resource in the Cloud Build API. At a high level, a `Build` describes where to find source code, how to build it (for example, the builder image to run on the source), and where to store the built artifacts. Fields can include the following variables, which will be expanded when the build is created: - $PROJECT_ID: the project ID of the build. - $PROJECT_NUMBER: the project number of the build. - $LOCATION: the location/region of the build. - $BUILD_ID: the autogenerated ID of the build. - $REPO_NAME: the source repository name specified by RepoSource. - $BRANCH_NAME: the branch name specified by RepoSource. - $TAG_NAME: the tag name specified by RepoSource. - $REVISION_ID or $COMMIT_SHA: the commit SHA specified by RepoSource or resolved from the specified branch or tag. - $SHORT_SHA: first 7 characters of $REVISION_ID or $COMMIT_SHA.
 *
 * Wraps the GCP resource as a swamp model so create, get, update,
 * delete, and sync can be driven through `swamp model`.
 *
 * @module
 */

import { z } from "npm:zod@4.3.6";
import {
  createResource,
  type ExplicitGcpCredentials,
  getProjectId,
  isResourceNotFoundError,
  listResources,
  readResource,
} from "./_lib/gcp.ts";

const BASE_URL = "https://cloudbuild.googleapis.com/";

const GET_CONFIG = {
  "id": "cloudbuild.projects.builds.get",
  "path": "v1/projects/{projectId}/builds/{id}",
  "httpMethod": "GET",
  "parameterOrder": [
    "projectId",
    "id",
  ],
  "parameters": {
    "id": {
      "location": "path",
      "required": true,
    },
    "name": {
      "location": "query",
    },
    "projectId": {
      "location": "path",
      "required": true,
    },
  },
} as const;

const INSERT_CONFIG = {
  "id": "cloudbuild.projects.builds.create",
  "path": "v1/projects/{projectId}/builds",
  "httpMethod": "POST",
  "parameterOrder": [
    "projectId",
  ],
  "parameters": {
    "parent": {
      "location": "query",
    },
    "projectId": {
      "location": "path",
      "required": true,
    },
  },
} as const;

const LIST_CONFIG = {
  "id": "cloudbuild.projects.builds.list",
  "path": "v1/projects/{projectId}/builds",
  "httpMethod": "GET",
  "parameterOrder": [
    "projectId",
  ],
  "parameters": {
    "filter": {
      "location": "query",
    },
    "pageSize": {
      "location": "query",
    },
    "pageToken": {
      "location": "query",
    },
    "parent": {
      "location": "query",
    },
    "projectId": {
      "location": "path",
      "required": true,
    },
  },
} as const;

const GlobalArgsSchema = z.object({
  name: z.string().describe(
    "Instance name for this resource (used as the unique identifier in the factory pattern)",
  ),
  accessToken: z.string().meta({ sensitive: true }).describe(
    "GCP OAuth2 access token; overrides GCP_ACCESS_TOKEN environment variable. Wire with a vault.get(...) expression to source it from a vault.",
  ).optional(),
  credentialsJson: z.string().meta({ sensitive: true }).describe(
    "GCP service account JSON credentials; overrides GOOGLE_APPLICATION_CREDENTIALS_JSON environment variable. Wire with a vault.get(...) expression to source it from a vault.",
  ).optional(),
  project: z.string().describe(
    "GCP project ID; overrides GCP_PROJECT / GOOGLE_CLOUD_PROJECT environment variables.",
  ).optional(),
  scopes: z.string().describe(
    "Comma-separated OAuth scopes to request when minting access tokens via gcloud. Defaults to the API's Discovery Document scopes.",
  ).optional(),
  quotaProject: z.string().describe(
    "GCP project ID for quota and billing attribution; sets the x-goog-user-project header. Overrides GOOGLE_CLOUD_QUOTA_PROJECT environment variable. Required for APIs like Cloud Identity when using user credentials.",
  ).optional(),
  apiEndpoint: z.string().describe(
    "Custom API endpoint for emulators; overrides GCP_API_ENDPOINT environment variable. Defaults to the service's production URL.",
  ).optional(),
  artifacts: z.object({
    genericArtifacts: z.array(z.object({
      folder: z.string().describe(
        "Required. Path to the generic artifact in the build's workspace to be uploaded to Artifact Registry.",
      ).optional(),
      registryPath: z.string().describe(
        "Required. Registry path to upload the generic artifact to, in the form projects/$PROJECT/locations/$LOCATION/repositories/$REPO/packages/$PACKAGE/versions/$VERSION",
      ).optional(),
    })).describe(
      "Optional. A list of generic artifacts to be uploaded to Artifact Registry upon successful completion of all build steps. If any artifacts fail to be pushed, the build is marked FAILURE.",
    ).optional(),
    goModules: z.array(z.object({
      modulePath: z.string().describe(
        'Optional. The Go module\'s "module path". e.g. example.com/foo/v2',
      ).optional(),
      moduleVersion: z.string().describe(
        "Optional. The Go module's semantic version in the form vX.Y.Z. e.g. v0.1.1 Pre-release identifiers can also be added by appending a dash and dot separated ASCII alphanumeric characters and hyphens. e.g. v0.2.3-alpha.x.12m.5",
      ).optional(),
      repositoryLocation: z.string().describe(
        "Optional. Location of the Artifact Registry repository. i.e. us-east1 Defaults to the build’s location.",
      ).optional(),
      repositoryName: z.string().describe(
        "Optional. Artifact Registry repository name. Specified Go modules will be zipped and uploaded to Artifact Registry with this location as a prefix. e.g. my-go-repo",
      ).optional(),
      repositoryProjectId: z.string().describe(
        "Optional. Project ID of the Artifact Registry repository. Defaults to the build project.",
      ).optional(),
      sourcePath: z.string().describe(
        "Optional. Source path of the go.mod file in the build's workspace. If not specified, this will default to the current directory. e.g. ~/code/go/mypackage",
      ).optional(),
    })).describe(
      "Optional. A list of Go modules to be uploaded to Artifact Registry upon successful completion of all build steps. If any objects fail to be pushed, the build is marked FAILURE.",
    ).optional(),
    images: z.array(z.string()).describe(
      "A list of images to be pushed upon the successful completion of all build steps. The images will be pushed using the builder service account's credentials. The digests of the pushed images will be stored in the Build resource's results field. If any of the images fail to be pushed, the build is marked FAILURE.",
    ).optional(),
    mavenArtifacts: z.array(z.object({
      artifactId: z.string().describe(
        "Maven `artifactId` value used when uploading the artifact to Artifact Registry.",
      ).optional(),
      deployFolder: z.string().describe(
        "Optional. Path to a folder containing the files to upload to Artifact Registry. This can be either an absolute path, e.g. `/workspace/my-app/target/`, or a relative path from /workspace, e.g. `my-app/target/`. This field is mutually exclusive with the `path` field.",
      ).optional(),
      groupId: z.string().describe(
        "Maven `groupId` value used when uploading the artifact to Artifact Registry.",
      ).optional(),
      path: z.string().describe(
        "Optional. Path to an artifact in the build's workspace to be uploaded to Artifact Registry. This can be either an absolute path, e.g. /workspace/my-app/target/my-app-1.0.SNAPSHOT.jar or a relative path from /workspace, e.g. my-app/target/my-app-1.0.SNAPSHOT.jar.",
      ).optional(),
      repository: z.string().describe(
        'Artifact Registry repository, in the form "https://$REGION-maven.pkg.dev/$PROJECT/$REPOSITORY" Artifact in the workspace specified by path will be uploaded to Artifact Registry with this location as a prefix.',
      ).optional(),
      version: z.string().describe(
        "Maven `version` value used when uploading the artifact to Artifact Registry.",
      ).optional(),
    })).describe(
      "A list of Maven artifacts to be uploaded to Artifact Registry upon successful completion of all build steps. Artifacts in the workspace matching specified paths globs will be uploaded to the specified Artifact Registry repository using the builder service account's credentials. If any artifacts fail to be pushed, the build is marked FAILURE.",
    ).optional(),
    npmPackages: z.array(z.object({
      packagePath: z.string().describe(
        "Optional. Path to the package.json. e.g. workspace/path/to/package Only one of `archive` or `package_path` can be specified.",
      ).optional(),
      repository: z.string().describe(
        'Artifact Registry repository, in the form "https://$REGION-npm.pkg.dev/$PROJECT/$REPOSITORY" Npm package in the workspace specified by path will be zipped and uploaded to Artifact Registry with this location as a prefix.',
      ).optional(),
    })).describe(
      "A list of npm packages to be uploaded to Artifact Registry upon successful completion of all build steps. Npm packages in the specified paths will be uploaded to the specified Artifact Registry repository using the builder service account's credentials. If any packages fail to be pushed, the build is marked FAILURE.",
    ).optional(),
    objects: z.object({
      location: z.string().describe(
        'Cloud Storage bucket and optional object path, in the form "gs://bucket/path/to/somewhere/". (see [Bucket Name Requirements](https://cloud.google.com/storage/docs/bucket-naming#requirements)). Files in the workspace matching any path pattern will be uploaded to Cloud Storage with this location as a prefix.',
      ).optional(),
      paths: z.array(z.string()).describe(
        "Path globs used to match files in the build's workspace.",
      ).optional(),
      timing: z.object({
        endTime: z.string().describe("End of time span.").optional(),
        startTime: z.string().describe("Start of time span.").optional(),
      }).describe(
        "Output only. Stores timing information for pushing all artifact objects.",
      ).optional(),
    }).describe(
      "A list of objects to be uploaded to Cloud Storage upon successful completion of all build steps. Files in the workspace matching specified paths globs will be uploaded to the specified Cloud Storage location using the builder service account's credentials. The location and generation of the uploaded objects will be stored in the Build resource's results field. If any objects fail to be pushed, the build is marked FAILURE.",
    ).optional(),
    oci: z.array(z.object({
      file: z.string().describe(
        "Required. Path on the local file system where to find the container to upload. e.g. /workspace/my-image.tar",
      ).optional(),
      registryPath: z.string().describe(
        "Required. Registry path to upload the container to. e.g. us-east1-docker.pkg.dev/my-project/my-repo/my-image",
      ).optional(),
      tags: z.array(z.string()).describe(
        "Optional. Tags to apply to the uploaded image. e.g. latest, 1.0.0",
      ).optional(),
    })).describe(
      "Optional. A list of OCI images to be uploaded to Artifact Registry upon successful completion of all build steps. OCI images in the specified paths will be uploaded to the specified Artifact Registry repository using the builder service account's credentials. If any images fail to be pushed, the build is marked FAILURE.",
    ).optional(),
    pythonPackages: z.array(z.object({
      paths: z.array(z.string()).describe(
        "Path globs used to match files in the build's workspace. For Python/ Twine, this is usually `dist/*`, and sometimes additionally an `.asc` file.",
      ).optional(),
      repository: z.string().describe(
        'Artifact Registry repository, in the form "https://$REGION-python.pkg.dev/$PROJECT/$REPOSITORY" Files in the workspace matching any path pattern will be uploaded to Artifact Registry with this location as a prefix.',
      ).optional(),
    })).describe(
      "A list of Python packages to be uploaded to Artifact Registry upon successful completion of all build steps. The build service account credentials will be used to perform the upload. If any objects fail to be pushed, the build is marked FAILURE.",
    ).optional(),
  }).describe(
    "Artifacts produced by the build that should be uploaded upon successful completion of all build steps.",
  ).optional(),
  availableSecrets: z.object({
    inline: z.array(z.object({
      envMap: z.record(z.string(), z.string()).describe(
        "Map of environment variable name to its encrypted value. Secret environment variables must be unique across all of a build's secrets, and must be used by at least one build step. Values can be at most 64 KB in size. There can be at most 100 secret values across all of a build's secrets.",
      ).optional(),
      kmsKeyName: z.string().describe(
        "Resource name of Cloud KMS crypto key to decrypt the encrypted value. In format: projects/*/locations/*/keyRings/*/cryptoKeys/*",
      ).optional(),
    })).describe(
      "Secrets encrypted with KMS key and the associated secret environment variable.",
    ).optional(),
    secretManager: z.array(z.object({
      env: z.string().describe(
        "Environment variable name to associate with the secret. Secret environment variables must be unique across all of a build's secrets, and must be used by at least one build step.",
      ).optional(),
      versionName: z.string().describe(
        "Resource name of the SecretVersion. In format: projects/*/secrets/*/versions/*",
      ).optional(),
    })).describe(
      "Secrets in Secret Manager and associated secret environment variable.",
    ).optional(),
  }).describe("Secrets and secret environment variables.").optional(),
  dependencies: z.array(z.object({
    empty: z.boolean().describe(
      "If set to true disable all dependency fetching (ignoring the default source as well).",
    ).optional(),
    genericArtifact: z.object({
      destPath: z.string().describe(
        "Required. Where the artifact files should be placed on the worker.",
      ).optional(),
      resource: z.string().describe(
        "Required. The location to download the artifact files from. Ex: projects/p1/locations/us/repositories/r1/packages/p1/versions/v1",
      ).optional(),
    }).describe("Represents a generic artifact as a build dependency.")
      .optional(),
    gitSource: z.object({
      depth: z.string().describe(
        "Optional. How much history should be fetched for the build (default 1, -1 for all history).",
      ).optional(),
      destPath: z.string().describe(
        "Required. Where should the files be placed on the worker.",
      ).optional(),
      fetchTags: z.boolean().describe(
        "Optional. True if remote tags should be fetched too (default false). Note: when depth is 1 (default), git fetch only retrieves tags pointing to commits within the shallow boundary. Set depth to -1 to fetch all historical tags.",
      ).optional(),
      recurseSubmodules: z.boolean().describe(
        "Optional. True if submodules should be fetched too (default false).",
      ).optional(),
      repository: z.object({
        developerConnect: z.string().describe(
          "The Developer Connect Git repository link formatted as `projects/*/locations/*/connections/*/gitRepositoryLink/*`",
        ).optional(),
        url: z.string().describe("Location of the Git repository.").optional(),
      }).describe("Required. The kind of repo (url or dev connect).")
        .optional(),
      revision: z.string().describe(
        "Required. The revision that we will fetch the repo at.",
      ).optional(),
    }).describe("Represents a git repository as a build dependency.")
      .optional(),
  })).describe(
    "Optional. Dependencies that the Cloud Build worker will fetch before executing user steps.",
  ).optional(),
  gitConfig: z.object({
    http: z.object({
      proxySecretVersionName: z.string().describe(
        "SecretVersion resource of the HTTP proxy URL. The Service Account used in the build (either the default Service Account or user-specified Service Account) should have `secretmanager.versions.access` permissions on this secret. The proxy URL should be in format `protocol://@]proxyhost[:port]`.",
      ).optional(),
    }).describe("Configuration for HTTP related git operations.").optional(),
  }).describe("Optional. Configuration for git operations.").optional(),
  images: z.array(z.string()).describe(
    "A list of images to be pushed upon the successful completion of all build steps. The images are pushed using the builder service account's credentials. The digests of the pushed images will be stored in the `Build` resource's results field. If any of the images fail to be pushed, the build status is marked `FAILURE`.",
  ).optional(),
  logsBucket: z.string().describe(
    "Cloud Storage bucket where logs should be written (see [Bucket Name Requirements](https://cloud.google.com/storage/docs/bucket-naming#requirements)). Logs file names will be of the format `${logs_bucket}/log-${build_id}.txt`.",
  ).optional(),
  options: z.object({
    automapSubstitutions: z.boolean().describe(
      "Option to include built-in and custom substitutions as env variables for all build steps.",
    ).optional(),
    defaultLogsBucketBehavior: z.enum([
      "DEFAULT_LOGS_BUCKET_BEHAVIOR_UNSPECIFIED",
      "REGIONAL_USER_OWNED_BUCKET",
      "LEGACY_BUCKET",
    ]).describe(
      "Optional. Option to specify how default logs buckets are setup.",
    ).optional(),
    diskSizeGb: z.string().describe(
      'Requested disk size for the VM that runs the build. Note that this is *NOT* "disk free"; some of the space will be used by the operating system and build utilities. Also note that this is the minimum disk size that will be allocated for the build -- the build may run with a larger disk than requested. At present, the maximum disk size is 4000GB; builds that request more than the maximum are rejected with an error.',
    ).optional(),
    dynamicSubstitutions: z.boolean().describe(
      "Option to specify whether or not to apply bash style string operations to the substitutions. NOTE: this is always enabled for triggered builds and cannot be overridden in the build configuration file.",
    ).optional(),
    enableStructuredLogging: z.boolean().describe(
      "Optional. Option to specify whether structured logging is enabled. If true, JSON-formatted logs are parsed as structured logs.",
    ).optional(),
    env: z.array(z.string()).describe(
      'A list of global environment variable definitions that will exist for all build steps in this build. If a variable is defined in both globally and in a build step, the variable will use the build step value. The elements are of the form "KEY=VALUE" for the environment variable "KEY" being given the value "VALUE".',
    ).optional(),
    logStreamingOption: z.enum(["STREAM_DEFAULT", "STREAM_ON", "STREAM_OFF"])
      .describe(
        "Option to define build log streaming behavior to Cloud Storage.",
      ).optional(),
    logging: z.enum([
      "LOGGING_UNSPECIFIED",
      "LEGACY",
      "GCS_ONLY",
      "STACKDRIVER_ONLY",
      "CLOUD_LOGGING_ONLY",
      "NONE",
    ]).describe(
      "Option to specify the logging mode, which determines if and where build logs are stored.",
    ).optional(),
    machineType: z.enum([
      "UNSPECIFIED",
      "N1_HIGHCPU_8",
      "N1_HIGHCPU_32",
      "E2_HIGHCPU_8",
      "E2_HIGHCPU_32",
      "E2_MEDIUM",
      "E2_STANDARD_2",
    ]).describe("Compute Engine machine type on which to run the build.")
      .optional(),
    pool: z.object({
      name: z.string().describe(
        "The `WorkerPool` resource to execute the build on. You must have `cloudbuild.workerpools.use` on the project hosting the WorkerPool. Format projects/{project}/locations/{location}/workerPools/{workerPoolId}",
      ).optional(),
      resolvedWorkerRelease: z.string().describe(
        "Output only. OUTPUT_ONLY. Worker release resolved from the release channel.",
      ).optional(),
      workerRelease: z.string().describe(
        "Output only. OUTPUT_ONLY. The release or release channel used to run the Build. This is set to the same value as `PrivatePoolV1Config.WorkerConfig.worker_release` for the UI to easily access.",
      ).optional(),
    }).describe(
      "Optional. Specification for execution on a `WorkerPool`. See [running builds in a private pool](https://cloud.google.com/build/docs/private-pools/run-builds-in-private-pool) for more information.",
    ).optional(),
    pubsubTopic: z.string().describe(
      "Optional. Option to specify the Pub/Sub topic to receive build status updates.",
    ).optional(),
    requestedVerifyOption: z.enum(["NOT_VERIFIED", "VERIFIED"]).describe(
      "Requested verifiability options.",
    ).optional(),
    resolvedWorkerRelease: z.string().describe(
      "Output only. Worker release resolved from the release channel.",
    ).optional(),
    secretEnv: z.array(z.string()).describe(
      "A list of global environment variables, which are encrypted using a Cloud Key Management Service crypto key. These values must be specified in the build's `Secret`. These variables will be available to all build steps in this build.",
    ).optional(),
    sourceProvenanceHash: z.array(
      z.enum([
        "NONE",
        "SHA256",
        "MD5",
        "GO_MODULE_H1",
        "SHA512",
        "DIRSUM_SHA256",
      ]),
    ).describe("Requested hash for SourceProvenance.").optional(),
    substitutionOption: z.enum(["MUST_MATCH", "ALLOW_LOOSE"]).describe(
      "Option to specify behavior when there is an error in the substitution checks. NOTE: this is always set to ALLOW_LOOSE for triggered builds and cannot be overridden in the build configuration file.",
    ).optional(),
    volumes: z.array(z.object({
      name: z.string().describe(
        "Name of the volume to mount. Volume names must be unique per build step and must be valid names for Docker volumes. Each named volume must be used by at least two build steps.",
      ).optional(),
      path: z.string().describe(
        "Path at which to mount the volume. Paths must be absolute and cannot conflict with other volume paths on the same build step or with certain reserved volume paths.",
      ).optional(),
    })).describe(
      "Global list of volumes to mount for ALL build steps Each volume is created as an empty volume prior to starting the build process. Upon completion of the build, volumes and their contents are discarded. Global volume names and paths cannot conflict with the volumes defined a build step. Using a global volume in a build with only one step is not valid as it is indicative of a build request with an incorrect configuration.",
    ).optional(),
    workerPool: z.string().describe(
      "This field deprecated; please use `pool.name` instead.",
    ).optional(),
    workerRelease: z.string().describe(
      "Optional. Option to specify which release or release channel (rapid|regular|stable) to use to run this build.",
    ).optional(),
  }).describe("Special options for this build.").optional(),
  projectId: z.string().describe("Output only. ID of the project.").optional(),
  queueTtl: z.string().describe(
    "TTL in queue for this build. If provided and the build is enqueued longer than this value, the build will expire and the build status will be `EXPIRED`. The TTL starts ticking from create_time.",
  ).optional(),
  secrets: z.array(z.object({
    kmsKeyName: z.string().describe(
      "Cloud KMS key name to use to decrypt these envs.",
    ).optional(),
    secretEnv: z.record(z.string(), z.string()).describe(
      "Map of environment variable name to its encrypted value. Secret environment variables must be unique across all of a build's secrets, and must be used by at least one build step. Values can be at most 64 KB in size. There can be at most 100 secret values across all of a build's secrets.",
    ).optional(),
  })).describe(
    "Secrets to decrypt using Cloud Key Management Service. Note: Secret Manager is the recommended technique for managing sensitive data with Cloud Build. Use `available_secrets` to configure builds to access secrets from Secret Manager. For instructions, see: https://cloud.google.com/cloud-build/docs/securing-builds/use-secrets",
  ).optional(),
  serviceAccount: z.string().describe(
    "IAM service account whose credentials will be used at build runtime. Must be of the format `projects/{PROJECT_ID}/serviceAccounts/{ACCOUNT}`. ACCOUNT can be email address or uniqueId of the service account.",
  ).optional(),
  source: z.object({
    connectedRepository: z.object({
      dir: z.string().describe(
        "Optional. Directory, relative to the source root, in which to run the build.",
      ).optional(),
      repository: z.string().describe(
        "Required. Name of the Google Cloud Build repository, formatted as `projects/*/locations/*/connections/*/repositories/*`.",
      ).optional(),
      revision: z.string().describe(
        "Required. The revision to fetch from the Git repository such as a branch, a tag, a commit SHA, or any Git ref.",
      ).optional(),
    }).describe(
      "Optional. If provided, get the source from this 2nd-gen Google Cloud Build repository resource.",
    ).optional(),
    developerConnectConfig: z.object({
      dir: z.string().describe(
        "Required. Directory, relative to the source root, in which to run the build.",
      ).optional(),
      gitRepositoryLink: z.string().describe(
        "Required. The Developer Connect Git repository link, formatted as `projects/*/locations/*/connections/*/gitRepositoryLink/*`.",
      ).optional(),
      revision: z.string().describe(
        "Required. The revision to fetch from the Git repository such as a branch, a tag, a commit SHA, or any Git ref.",
      ).optional(),
    }).describe(
      "If provided, get the source from this Developer Connect config.",
    ).optional(),
    gitSource: z.object({
      dir: z.string().describe(
        "Optional. Directory, relative to the source root, in which to run the build. This must be a relative path. If a step's `dir` is specified and is an absolute path, this value is ignored for that step's execution.",
      ).optional(),
      revision: z.string().describe(
        "Optional. The revision to fetch from the Git repository such as a branch, a tag, a commit SHA, or any Git ref. Cloud Build uses `git fetch` to fetch the revision from the Git repository; therefore make sure that the string you provide for `revision` is parsable by the command. For information on string values accepted by `git fetch`, see https://git-scm.com/docs/gitrevisions#_specifying_revisions. For information on `git fetch`, see https://git-scm.com/docs/git-fetch.",
      ).optional(),
      url: z.string().describe(
        "Required. Location of the Git repo to build. This will be used as a `git remote`, see https://git-scm.com/docs/git-remote.",
      ).optional(),
    }).describe("If provided, get the source from this Git repository.")
      .optional(),
    repoSource: z.object({
      branchName: z.string().describe(
        "Regex matching branches to build. The syntax of the regular expressions accepted is the syntax accepted by RE2 and described at https://github.com/google/re2/wiki/Syntax",
      ).optional(),
      commitSha: z.string().describe("Explicit commit SHA to build.")
        .optional(),
      dir: z.string().describe(
        "Optional. Directory, relative to the source root, in which to run the build. This must be a relative path. If a step's `dir` is specified and is an absolute path, this value is ignored for that step's execution.",
      ).optional(),
      invertRegex: z.boolean().describe(
        "Optional. Only trigger a build if the revision regex does NOT match the revision regex.",
      ).optional(),
      projectId: z.string().describe(
        "Optional. ID of the project that owns the Cloud Source Repository. If omitted, the project ID requesting the build is assumed.",
      ).optional(),
      repoName: z.string().describe(
        "Required. Name of the Cloud Source Repository.",
      ).optional(),
      substitutions: z.record(z.string(), z.string()).describe(
        "Optional. Substitutions to use in a triggered build. Should only be used with RunBuildTrigger",
      ).optional(),
      tagName: z.string().describe(
        "Regex matching tags to build. The syntax of the regular expressions accepted is the syntax accepted by RE2 and described at https://github.com/google/re2/wiki/Syntax",
      ).optional(),
    }).describe(
      "If provided, get the source from this location in a Cloud Source Repository.",
    ).optional(),
    storageSource: z.object({
      bucket: z.string().describe(
        "Cloud Storage bucket containing the source (see [Bucket Name Requirements](https://cloud.google.com/storage/docs/bucket-naming#requirements)).",
      ).optional(),
      generation: z.string().describe(
        "Optional. Cloud Storage generation for the object. If the generation is omitted, the latest generation will be used.",
      ).optional(),
      object: z.string().describe(
        "Required. Cloud Storage object containing the source. This object must be a zipped (`.zip`) or gzipped archive file (`.tar.gz`) containing source to build.",
      ).optional(),
      sourceFetcher: z.enum([
        "SOURCE_FETCHER_UNSPECIFIED",
        "GSUTIL",
        "GCS_FETCHER",
      ]).describe(
        "Optional. Option to specify the tool to fetch the source file for the build.",
      ).optional(),
    }).describe(
      "If provided, get the source from this location in Cloud Storage.",
    ).optional(),
    storageSourceManifest: z.object({
      bucket: z.string().describe(
        "Required. Cloud Storage bucket containing the source manifest (see [Bucket Name Requirements](https://cloud.google.com/storage/docs/bucket-naming#requirements)).",
      ).optional(),
      generation: z.string().describe(
        "Cloud Storage generation for the object. If the generation is omitted, the latest generation will be used.",
      ).optional(),
      object: z.string().describe(
        "Required. Cloud Storage object containing the source manifest. This object must be a JSON file.",
      ).optional(),
    }).describe(
      "If provided, get the source from this manifest in Cloud Storage. This feature is in Preview; see description [here](https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/gcs-fetcher).",
    ).optional(),
  }).describe("Optional. The location of the source files to build.")
    .optional(),
  steps: z.array(z.object({
    allowExitCodes: z.array(z.number().int()).describe(
      "Allow this build step to fail without failing the entire build if and only if the exit code is one of the specified codes. If allow_failure is also specified, this field will take precedence.",
    ).optional(),
    allowFailure: z.boolean().describe(
      "Allow this build step to fail without failing the entire build. If false, the entire build will fail if this step fails. Otherwise, the build will succeed, but this step will still have a failure status. Error information will be reported in the failure_detail field.",
    ).optional(),
    args: z.array(z.string()).describe(
      "A list of arguments that will be presented to the step when it is started. If the image used to run the step's container has an entrypoint, the `args` are used as arguments to that entrypoint. If the image does not define an entrypoint, the first element in args is used as the entrypoint, and the remainder will be used as arguments.",
    ).optional(),
    automapSubstitutions: z.boolean().describe(
      "Option to include built-in and custom substitutions as env variables for this build step. This option will override the global option in BuildOption.",
    ).optional(),
    dir: z.string().describe(
      "Working directory to use when running this step's container. If this value is a relative path, it is relative to the build's working directory. If this value is absolute, it may be outside the build's working directory, in which case the contents of the path may not be persisted across build step executions, unless a `volume` for that path is specified. If the build specifies a `RepoSource` with `dir` and a step with a `dir`, which specifies an absolute path, the `RepoSource` `dir` is ignored for the step's execution.",
    ).optional(),
    entrypoint: z.string().describe(
      "Entrypoint to be used instead of the build step image's default entrypoint. If unset, the image's default entrypoint is used.",
    ).optional(),
    env: z.array(z.string()).describe(
      'A list of environment variable definitions to be used when running a step. The elements are of the form "KEY=VALUE" for the environment variable "KEY" being given the value "VALUE".',
    ).optional(),
    exitCode: z.number().int().describe(
      "Output only. Return code from running the step.",
    ).optional(),
    id: z.string().describe(
      "Unique identifier for this build step, used in `wait_for` to reference this build step as a dependency.",
    ).optional(),
    name: z.string().describe(
      "Required. The name of the container image that will run this particular build step. If the image is available in the host's Docker daemon's cache, it will be run directly. If not, the host will attempt to pull the image first, using the builder service account's credentials if necessary. The Docker daemon's cache will already have the latest versions of all of the officially supported build steps ([https://github.com/GoogleCloudPlatform/cloud-builders](https://github.com/GoogleCloudPlatform/cloud-builders)). The Docker daemon will also have cached many of the layers for some popular images, like \"ubuntu\", \"debian\", but they will be refreshed at the time you attempt to use them. If you built an image in a previous build step, it will be stored in the host's Docker daemon's cache and is available to use as the name for a later build step.",
    ).optional(),
    pullTiming: z.object({
      endTime: z.string().describe("End of time span.").optional(),
      startTime: z.string().describe("Start of time span.").optional(),
    }).describe(
      "Output only. Stores timing information for pulling this build step's builder image only.",
    ).optional(),
    results: z.array(z.object({
      attestationContent: z.string().describe(
        "Optional. The content of the attestation to be generated.",
      ).optional(),
      attestationType: z.string().describe(
        "Optional. The type of attestation to be generated.",
      ).optional(),
      name: z.string().describe("Required. The name of the result.").optional(),
    })).describe("Declaration of results for this build step.").optional(),
    script: z.string().describe(
      "A shell script to be executed in the step. When script is provided, the user cannot specify the entrypoint or args.",
    ).optional(),
    secretEnv: z.array(z.string()).describe(
      "A list of environment variables which are encrypted using a Cloud Key Management Service crypto key. These values must be specified in the build's `Secret`.",
    ).optional(),
    status: z.enum([
      "STATUS_UNKNOWN",
      "PENDING",
      "QUEUED",
      "WORKING",
      "SUCCESS",
      "FAILURE",
      "INTERNAL_ERROR",
      "TIMEOUT",
      "CANCELLED",
      "EXPIRED",
    ]).describe(
      "Output only. Status of the build step. At this time, build step status is only updated on build completion; step status is not updated in real-time as the build progresses.",
    ).optional(),
    timeout: z.string().describe(
      "Time limit for executing this build step. If not defined, the step has no time limit and will be allowed to continue to run until either it completes or the build itself times out.",
    ).optional(),
    timing: z.object({
      endTime: z.string().describe("End of time span.").optional(),
      startTime: z.string().describe("Start of time span.").optional(),
    }).describe(
      "Output only. Stores timing information for executing this build step.",
    ).optional(),
    volumes: z.array(z.object({
      name: z.string().describe(
        "Name of the volume to mount. Volume names must be unique per build step and must be valid names for Docker volumes. Each named volume must be used by at least two build steps.",
      ).optional(),
      path: z.string().describe(
        "Path at which to mount the volume. Paths must be absolute and cannot conflict with other volume paths on the same build step or with certain reserved volume paths.",
      ).optional(),
    })).describe(
      "List of volumes to mount into the build step. Each volume is created as an empty volume prior to execution of the build step. Upon completion of the build, volumes and their contents are discarded. Using a named volume in only one step is not valid as it is indicative of a build request with an incorrect configuration.",
    ).optional(),
    waitFor: z.array(z.string()).describe(
      "The ID(s) of the step(s) that this build step depends on. This build step will not start until all the build steps in `wait_for` have completed successfully. If `wait_for` is empty, this build step will start when all previous build steps in the `Build.Steps` list have completed successfully.",
    ).optional(),
  })).describe("Required. The operations to be performed on the workspace.")
    .optional(),
  substitutions: z.record(z.string(), z.string()).describe(
    "Substitutions data for `Build` resource.",
  ).optional(),
  tags: z.array(z.string()).describe(
    "Tags for annotation of a `Build`. These are not docker tags.",
  ).optional(),
  timeout: z.string().describe(
    "Amount of time that this build should be allowed to run, to second granularity. If this amount of time elapses, work on the build will cease and the build status will be `TIMEOUT`. `timeout` starts ticking from `startTime`. Default time is 60 minutes.",
  ).optional(),
  parent: z.string().describe(
    "The parent resource where this build will be created. Format: `projects/{project}/locations/{location}`",
  ).optional(),
});

const StateSchema = z.object({
  approval: z.object({
    config: z.object({
      approvalRequired: z.boolean(),
    }),
    result: z.object({
      approvalTime: z.string(),
      approverAccount: z.string(),
      comment: z.string(),
      decision: z.string(),
      url: z.string(),
    }),
    state: z.string(),
  }).optional(),
  artifacts: z.object({
    genericArtifacts: z.array(z.object({
      folder: z.string(),
      registryPath: z.string(),
    })),
    goModules: z.array(z.object({
      modulePath: z.string(),
      moduleVersion: z.string(),
      repositoryLocation: z.string(),
      repositoryName: z.string(),
      repositoryProjectId: z.string(),
      sourcePath: z.string(),
    })),
    images: z.array(z.string()),
    mavenArtifacts: z.array(z.object({
      artifactId: z.string(),
      deployFolder: z.string(),
      groupId: z.string(),
      path: z.string(),
      repository: z.string(),
      version: z.string(),
    })),
    npmPackages: z.array(z.object({
      packagePath: z.string(),
      repository: z.string(),
    })),
    objects: z.object({
      location: z.string(),
      paths: z.array(z.string()),
      timing: z.object({
        endTime: z.string(),
        startTime: z.string(),
      }),
    }),
    oci: z.array(z.object({
      file: z.string(),
      registryPath: z.string(),
      tags: z.array(z.string()),
    })),
    pythonPackages: z.array(z.object({
      paths: z.array(z.string()),
      repository: z.string(),
    })),
  }).optional(),
  availableSecrets: z.object({
    inline: z.array(z.object({
      envMap: z.record(z.string(), z.unknown()),
      kmsKeyName: z.string(),
    })),
    secretManager: z.array(z.object({
      env: z.string(),
      versionName: z.string(),
    })),
  }).optional(),
  buildTriggerId: z.string().optional(),
  createTime: z.string().optional(),
  dependencies: z.array(z.object({
    empty: z.boolean(),
    genericArtifact: z.object({
      destPath: z.string(),
      resource: z.string(),
    }),
    gitSource: z.object({
      depth: z.string(),
      destPath: z.string(),
      fetchTags: z.boolean(),
      recurseSubmodules: z.boolean(),
      repository: z.object({
        developerConnect: z.string(),
        url: z.string(),
      }),
      revision: z.string(),
    }),
  })).optional(),
  failureInfo: z.object({
    detail: z.string(),
    type: z.string(),
  }).optional(),
  finishTime: z.string().optional(),
  gitConfig: z.object({
    http: z.object({
      proxySecretVersionName: z.string(),
    }),
  }).optional(),
  id: z.string(),
  images: z.array(z.string()).optional(),
  logUrl: z.string().optional(),
  logsBucket: z.string().optional(),
  name: z.string().optional(),
  options: z.object({
    automapSubstitutions: z.boolean(),
    defaultLogsBucketBehavior: z.string(),
    diskSizeGb: z.string(),
    dynamicSubstitutions: z.boolean(),
    enableStructuredLogging: z.boolean(),
    env: z.array(z.string()),
    logStreamingOption: z.string(),
    logging: z.string(),
    machineType: z.string(),
    pool: z.object({
      name: z.string(),
      resolvedWorkerRelease: z.string(),
      workerRelease: z.string(),
    }),
    pubsubTopic: z.string(),
    requestedVerifyOption: z.string(),
    resolvedWorkerRelease: z.string(),
    secretEnv: z.array(z.string()),
    sourceProvenanceHash: z.array(z.string()),
    substitutionOption: z.string(),
    volumes: z.array(z.object({
      name: z.string(),
      path: z.string(),
    })),
    workerPool: z.string(),
    workerRelease: z.string(),
  }).optional(),
  projectId: z.string().optional(),
  queueTtl: z.string().optional(),
  results: z.object({
    artifactManifest: z.string(),
    artifactTiming: z.object({
      endTime: z.string(),
      startTime: z.string(),
    }),
    buildStepImages: z.array(z.string()),
    buildStepOutputs: z.array(z.string()),
    buildStepResults: z.record(z.string(), z.unknown()),
    genericArtifacts: z.array(z.object({
      artifactFingerprint: z.object({
        fileHash: z.array(z.unknown()),
      }),
      artifactRegistryPackage: z.string(),
      fileHashes: z.record(z.string(), z.unknown()),
      pushTiming: z.object({
        endTime: z.string(),
        startTime: z.string(),
      }),
      uri: z.string(),
    })),
    goModules: z.array(z.object({
      artifactRegistryPackage: z.string(),
      fileHashes: z.object({
        fileHash: z.array(z.unknown()),
      }),
      pushTiming: z.object({
        endTime: z.string(),
        startTime: z.string(),
      }),
      uri: z.string(),
    })),
    images: z.array(z.object({
      artifactRegistryPackage: z.string(),
      digest: z.string(),
      name: z.string(),
      ociMediaType: z.string(),
      pushTiming: z.object({
        endTime: z.string(),
        startTime: z.string(),
      }),
    })),
    mavenArtifacts: z.array(z.object({
      artifactRegistryPackage: z.string(),
      fileHashes: z.object({
        fileHash: z.array(z.unknown()),
      }),
      pushTiming: z.object({
        endTime: z.string(),
        startTime: z.string(),
      }),
      uri: z.string(),
    })),
    npmPackages: z.array(z.object({
      artifactRegistryPackage: z.string(),
      fileHashes: z.object({
        fileHash: z.array(z.unknown()),
      }),
      pushTiming: z.object({
        endTime: z.string(),
        startTime: z.string(),
      }),
      uri: z.string(),
    })),
    numArtifacts: z.string(),
    pythonPackages: z.array(z.object({
      artifactRegistryPackage: z.string(),
      fileHashes: z.object({
        fileHash: z.array(z.unknown()),
      }),
      pushTiming: z.object({
        endTime: z.string(),
        startTime: z.string(),
      }),
      uri: z.string(),
    })),
  }).optional(),
  secrets: z.array(z.object({
    kmsKeyName: z.string(),
    secretEnv: z.record(z.string(), z.unknown()),
  })).optional(),
  serviceAccount: z.string().optional(),
  source: z.object({
    connectedRepository: z.object({
      dir: z.string(),
      repository: z.string(),
      revision: z.string(),
    }),
    developerConnectConfig: z.object({
      dir: z.string(),
      gitRepositoryLink: z.string(),
      revision: z.string(),
    }),
    gitSource: z.object({
      dir: z.string(),
      revision: z.string(),
      url: z.string(),
    }),
    repoSource: z.object({
      branchName: z.string(),
      commitSha: z.string(),
      dir: z.string(),
      invertRegex: z.boolean(),
      projectId: z.string(),
      repoName: z.string(),
      substitutions: z.record(z.string(), z.unknown()),
      tagName: z.string(),
    }),
    storageSource: z.object({
      bucket: z.string(),
      generation: z.string(),
      object: z.string(),
      sourceFetcher: z.string(),
    }),
    storageSourceManifest: z.object({
      bucket: z.string(),
      generation: z.string(),
      object: z.string(),
    }),
  }).optional(),
  sourceProvenance: z.object({
    fileHashes: z.record(z.string(), z.unknown()),
    resolvedConnectedRepository: z.object({
      dir: z.string(),
      repository: z.string(),
      revision: z.string(),
    }),
    resolvedGitSource: z.object({
      dir: z.string(),
      revision: z.string(),
      url: z.string(),
    }),
    resolvedRepoSource: z.object({
      branchName: z.string(),
      commitSha: z.string(),
      dir: z.string(),
      invertRegex: z.boolean(),
      projectId: z.string(),
      repoName: z.string(),
      substitutions: z.record(z.string(), z.unknown()),
      tagName: z.string(),
    }),
    resolvedStorageSource: z.object({
      bucket: z.string(),
      generation: z.string(),
      object: z.string(),
      sourceFetcher: z.string(),
    }),
    resolvedStorageSourceManifest: z.object({
      bucket: z.string(),
      generation: z.string(),
      object: z.string(),
    }),
  }).optional(),
  startTime: z.string().optional(),
  status: z.string().optional(),
  statusDetail: z.string().optional(),
  steps: z.array(z.object({
    allowExitCodes: z.array(z.number()),
    allowFailure: z.boolean(),
    args: z.array(z.string()),
    automapSubstitutions: z.boolean(),
    dir: z.string(),
    entrypoint: z.string(),
    env: z.array(z.string()),
    exitCode: z.number(),
    id: z.string(),
    name: z.string(),
    pullTiming: z.object({
      endTime: z.string(),
      startTime: z.string(),
    }),
    results: z.array(z.object({
      attestationContent: z.string(),
      attestationType: z.string(),
      name: z.string(),
    })),
    script: z.string(),
    secretEnv: z.array(z.string()),
    status: z.string(),
    timeout: z.string(),
    timing: z.object({
      endTime: z.string(),
      startTime: z.string(),
    }),
    volumes: z.array(z.object({
      name: z.string(),
      path: z.string(),
    })),
    waitFor: z.array(z.string()),
  })).optional(),
  substitutions: z.record(z.string(), z.unknown()).optional(),
  tags: z.array(z.string()).optional(),
  timeout: z.string().optional(),
  timing: z.record(z.string(), z.unknown()).optional(),
  warnings: z.array(z.object({
    priority: z.string(),
    text: z.string(),
  })).optional(),
}).passthrough();

type StateData = z.infer<typeof StateSchema>;

const InputsSchema = z.object({
  name: z.string().optional(),
  accessToken: z.string().meta({ sensitive: true }).optional(),
  credentialsJson: z.string().meta({ sensitive: true }).optional(),
  project: z.string().optional(),
  scopes: z.string().optional(),
  quotaProject: z.string().optional(),
  apiEndpoint: z.string().optional(),
  artifacts: z.object({
    genericArtifacts: z.array(z.object({
      folder: z.string().describe(
        "Required. Path to the generic artifact in the build's workspace to be uploaded to Artifact Registry.",
      ).optional(),
      registryPath: z.string().describe(
        "Required. Registry path to upload the generic artifact to, in the form projects/$PROJECT/locations/$LOCATION/repositories/$REPO/packages/$PACKAGE/versions/$VERSION",
      ).optional(),
    })).describe(
      "Optional. A list of generic artifacts to be uploaded to Artifact Registry upon successful completion of all build steps. If any artifacts fail to be pushed, the build is marked FAILURE.",
    ).optional(),
    goModules: z.array(z.object({
      modulePath: z.string().describe(
        'Optional. The Go module\'s "module path". e.g. example.com/foo/v2',
      ).optional(),
      moduleVersion: z.string().describe(
        "Optional. The Go module's semantic version in the form vX.Y.Z. e.g. v0.1.1 Pre-release identifiers can also be added by appending a dash and dot separated ASCII alphanumeric characters and hyphens. e.g. v0.2.3-alpha.x.12m.5",
      ).optional(),
      repositoryLocation: z.string().describe(
        "Optional. Location of the Artifact Registry repository. i.e. us-east1 Defaults to the build’s location.",
      ).optional(),
      repositoryName: z.string().describe(
        "Optional. Artifact Registry repository name. Specified Go modules will be zipped and uploaded to Artifact Registry with this location as a prefix. e.g. my-go-repo",
      ).optional(),
      repositoryProjectId: z.string().describe(
        "Optional. Project ID of the Artifact Registry repository. Defaults to the build project.",
      ).optional(),
      sourcePath: z.string().describe(
        "Optional. Source path of the go.mod file in the build's workspace. If not specified, this will default to the current directory. e.g. ~/code/go/mypackage",
      ).optional(),
    })).describe(
      "Optional. A list of Go modules to be uploaded to Artifact Registry upon successful completion of all build steps. If any objects fail to be pushed, the build is marked FAILURE.",
    ).optional(),
    images: z.array(z.string()).describe(
      "A list of images to be pushed upon the successful completion of all build steps. The images will be pushed using the builder service account's credentials. The digests of the pushed images will be stored in the Build resource's results field. If any of the images fail to be pushed, the build is marked FAILURE.",
    ).optional(),
    mavenArtifacts: z.array(z.object({
      artifactId: z.string().describe(
        "Maven `artifactId` value used when uploading the artifact to Artifact Registry.",
      ).optional(),
      deployFolder: z.string().describe(
        "Optional. Path to a folder containing the files to upload to Artifact Registry. This can be either an absolute path, e.g. `/workspace/my-app/target/`, or a relative path from /workspace, e.g. `my-app/target/`. This field is mutually exclusive with the `path` field.",
      ).optional(),
      groupId: z.string().describe(
        "Maven `groupId` value used when uploading the artifact to Artifact Registry.",
      ).optional(),
      path: z.string().describe(
        "Optional. Path to an artifact in the build's workspace to be uploaded to Artifact Registry. This can be either an absolute path, e.g. /workspace/my-app/target/my-app-1.0.SNAPSHOT.jar or a relative path from /workspace, e.g. my-app/target/my-app-1.0.SNAPSHOT.jar.",
      ).optional(),
      repository: z.string().describe(
        'Artifact Registry repository, in the form "https://$REGION-maven.pkg.dev/$PROJECT/$REPOSITORY" Artifact in the workspace specified by path will be uploaded to Artifact Registry with this location as a prefix.',
      ).optional(),
      version: z.string().describe(
        "Maven `version` value used when uploading the artifact to Artifact Registry.",
      ).optional(),
    })).describe(
      "A list of Maven artifacts to be uploaded to Artifact Registry upon successful completion of all build steps. Artifacts in the workspace matching specified paths globs will be uploaded to the specified Artifact Registry repository using the builder service account's credentials. If any artifacts fail to be pushed, the build is marked FAILURE.",
    ).optional(),
    npmPackages: z.array(z.object({
      packagePath: z.string().describe(
        "Optional. Path to the package.json. e.g. workspace/path/to/package Only one of `archive` or `package_path` can be specified.",
      ).optional(),
      repository: z.string().describe(
        'Artifact Registry repository, in the form "https://$REGION-npm.pkg.dev/$PROJECT/$REPOSITORY" Npm package in the workspace specified by path will be zipped and uploaded to Artifact Registry with this location as a prefix.',
      ).optional(),
    })).describe(
      "A list of npm packages to be uploaded to Artifact Registry upon successful completion of all build steps. Npm packages in the specified paths will be uploaded to the specified Artifact Registry repository using the builder service account's credentials. If any packages fail to be pushed, the build is marked FAILURE.",
    ).optional(),
    objects: z.object({
      location: z.string().describe(
        'Cloud Storage bucket and optional object path, in the form "gs://bucket/path/to/somewhere/". (see [Bucket Name Requirements](https://cloud.google.com/storage/docs/bucket-naming#requirements)). Files in the workspace matching any path pattern will be uploaded to Cloud Storage with this location as a prefix.',
      ).optional(),
      paths: z.array(z.string()).describe(
        "Path globs used to match files in the build's workspace.",
      ).optional(),
      timing: z.object({
        endTime: z.string().describe("End of time span.").optional(),
        startTime: z.string().describe("Start of time span.").optional(),
      }).describe(
        "Output only. Stores timing information for pushing all artifact objects.",
      ).optional(),
    }).describe(
      "A list of objects to be uploaded to Cloud Storage upon successful completion of all build steps. Files in the workspace matching specified paths globs will be uploaded to the specified Cloud Storage location using the builder service account's credentials. The location and generation of the uploaded objects will be stored in the Build resource's results field. If any objects fail to be pushed, the build is marked FAILURE.",
    ).optional(),
    oci: z.array(z.object({
      file: z.string().describe(
        "Required. Path on the local file system where to find the container to upload. e.g. /workspace/my-image.tar",
      ).optional(),
      registryPath: z.string().describe(
        "Required. Registry path to upload the container to. e.g. us-east1-docker.pkg.dev/my-project/my-repo/my-image",
      ).optional(),
      tags: z.array(z.string()).describe(
        "Optional. Tags to apply to the uploaded image. e.g. latest, 1.0.0",
      ).optional(),
    })).describe(
      "Optional. A list of OCI images to be uploaded to Artifact Registry upon successful completion of all build steps. OCI images in the specified paths will be uploaded to the specified Artifact Registry repository using the builder service account's credentials. If any images fail to be pushed, the build is marked FAILURE.",
    ).optional(),
    pythonPackages: z.array(z.object({
      paths: z.array(z.string()).describe(
        "Path globs used to match files in the build's workspace. For Python/ Twine, this is usually `dist/*`, and sometimes additionally an `.asc` file.",
      ).optional(),
      repository: z.string().describe(
        'Artifact Registry repository, in the form "https://$REGION-python.pkg.dev/$PROJECT/$REPOSITORY" Files in the workspace matching any path pattern will be uploaded to Artifact Registry with this location as a prefix.',
      ).optional(),
    })).describe(
      "A list of Python packages to be uploaded to Artifact Registry upon successful completion of all build steps. The build service account credentials will be used to perform the upload. If any objects fail to be pushed, the build is marked FAILURE.",
    ).optional(),
  }).describe(
    "Artifacts produced by the build that should be uploaded upon successful completion of all build steps.",
  ).optional(),
  availableSecrets: z.object({
    inline: z.array(z.object({
      envMap: z.record(z.string(), z.string()).describe(
        "Map of environment variable name to its encrypted value. Secret environment variables must be unique across all of a build's secrets, and must be used by at least one build step. Values can be at most 64 KB in size. There can be at most 100 secret values across all of a build's secrets.",
      ).optional(),
      kmsKeyName: z.string().describe(
        "Resource name of Cloud KMS crypto key to decrypt the encrypted value. In format: projects/*/locations/*/keyRings/*/cryptoKeys/*",
      ).optional(),
    })).describe(
      "Secrets encrypted with KMS key and the associated secret environment variable.",
    ).optional(),
    secretManager: z.array(z.object({
      env: z.string().describe(
        "Environment variable name to associate with the secret. Secret environment variables must be unique across all of a build's secrets, and must be used by at least one build step.",
      ).optional(),
      versionName: z.string().describe(
        "Resource name of the SecretVersion. In format: projects/*/secrets/*/versions/*",
      ).optional(),
    })).describe(
      "Secrets in Secret Manager and associated secret environment variable.",
    ).optional(),
  }).describe("Secrets and secret environment variables.").optional(),
  dependencies: z.array(z.object({
    empty: z.boolean().describe(
      "If set to true disable all dependency fetching (ignoring the default source as well).",
    ).optional(),
    genericArtifact: z.object({
      destPath: z.string().describe(
        "Required. Where the artifact files should be placed on the worker.",
      ).optional(),
      resource: z.string().describe(
        "Required. The location to download the artifact files from. Ex: projects/p1/locations/us/repositories/r1/packages/p1/versions/v1",
      ).optional(),
    }).describe("Represents a generic artifact as a build dependency.")
      .optional(),
    gitSource: z.object({
      depth: z.string().describe(
        "Optional. How much history should be fetched for the build (default 1, -1 for all history).",
      ).optional(),
      destPath: z.string().describe(
        "Required. Where should the files be placed on the worker.",
      ).optional(),
      fetchTags: z.boolean().describe(
        "Optional. True if remote tags should be fetched too (default false). Note: when depth is 1 (default), git fetch only retrieves tags pointing to commits within the shallow boundary. Set depth to -1 to fetch all historical tags.",
      ).optional(),
      recurseSubmodules: z.boolean().describe(
        "Optional. True if submodules should be fetched too (default false).",
      ).optional(),
      repository: z.object({
        developerConnect: z.string().describe(
          "The Developer Connect Git repository link formatted as `projects/*/locations/*/connections/*/gitRepositoryLink/*`",
        ).optional(),
        url: z.string().describe("Location of the Git repository.").optional(),
      }).describe("Required. The kind of repo (url or dev connect).")
        .optional(),
      revision: z.string().describe(
        "Required. The revision that we will fetch the repo at.",
      ).optional(),
    }).describe("Represents a git repository as a build dependency.")
      .optional(),
  })).describe(
    "Optional. Dependencies that the Cloud Build worker will fetch before executing user steps.",
  ).optional(),
  gitConfig: z.object({
    http: z.object({
      proxySecretVersionName: z.string().describe(
        "SecretVersion resource of the HTTP proxy URL. The Service Account used in the build (either the default Service Account or user-specified Service Account) should have `secretmanager.versions.access` permissions on this secret. The proxy URL should be in format `protocol://@]proxyhost[:port]`.",
      ).optional(),
    }).describe("Configuration for HTTP related git operations.").optional(),
  }).describe("Optional. Configuration for git operations.").optional(),
  images: z.array(z.string()).describe(
    "A list of images to be pushed upon the successful completion of all build steps. The images are pushed using the builder service account's credentials. The digests of the pushed images will be stored in the `Build` resource's results field. If any of the images fail to be pushed, the build status is marked `FAILURE`.",
  ).optional(),
  logsBucket: z.string().describe(
    "Cloud Storage bucket where logs should be written (see [Bucket Name Requirements](https://cloud.google.com/storage/docs/bucket-naming#requirements)). Logs file names will be of the format `${logs_bucket}/log-${build_id}.txt`.",
  ).optional(),
  options: z.object({
    automapSubstitutions: z.boolean().describe(
      "Option to include built-in and custom substitutions as env variables for all build steps.",
    ).optional(),
    defaultLogsBucketBehavior: z.enum([
      "DEFAULT_LOGS_BUCKET_BEHAVIOR_UNSPECIFIED",
      "REGIONAL_USER_OWNED_BUCKET",
      "LEGACY_BUCKET",
    ]).describe(
      "Optional. Option to specify how default logs buckets are setup.",
    ).optional(),
    diskSizeGb: z.string().describe(
      'Requested disk size for the VM that runs the build. Note that this is *NOT* "disk free"; some of the space will be used by the operating system and build utilities. Also note that this is the minimum disk size that will be allocated for the build -- the build may run with a larger disk than requested. At present, the maximum disk size is 4000GB; builds that request more than the maximum are rejected with an error.',
    ).optional(),
    dynamicSubstitutions: z.boolean().describe(
      "Option to specify whether or not to apply bash style string operations to the substitutions. NOTE: this is always enabled for triggered builds and cannot be overridden in the build configuration file.",
    ).optional(),
    enableStructuredLogging: z.boolean().describe(
      "Optional. Option to specify whether structured logging is enabled. If true, JSON-formatted logs are parsed as structured logs.",
    ).optional(),
    env: z.array(z.string()).describe(
      'A list of global environment variable definitions that will exist for all build steps in this build. If a variable is defined in both globally and in a build step, the variable will use the build step value. The elements are of the form "KEY=VALUE" for the environment variable "KEY" being given the value "VALUE".',
    ).optional(),
    logStreamingOption: z.enum(["STREAM_DEFAULT", "STREAM_ON", "STREAM_OFF"])
      .describe(
        "Option to define build log streaming behavior to Cloud Storage.",
      ).optional(),
    logging: z.enum([
      "LOGGING_UNSPECIFIED",
      "LEGACY",
      "GCS_ONLY",
      "STACKDRIVER_ONLY",
      "CLOUD_LOGGING_ONLY",
      "NONE",
    ]).describe(
      "Option to specify the logging mode, which determines if and where build logs are stored.",
    ).optional(),
    machineType: z.enum([
      "UNSPECIFIED",
      "N1_HIGHCPU_8",
      "N1_HIGHCPU_32",
      "E2_HIGHCPU_8",
      "E2_HIGHCPU_32",
      "E2_MEDIUM",
      "E2_STANDARD_2",
    ]).describe("Compute Engine machine type on which to run the build.")
      .optional(),
    pool: z.object({
      name: z.string().describe(
        "The `WorkerPool` resource to execute the build on. You must have `cloudbuild.workerpools.use` on the project hosting the WorkerPool. Format projects/{project}/locations/{location}/workerPools/{workerPoolId}",
      ).optional(),
      resolvedWorkerRelease: z.string().describe(
        "Output only. OUTPUT_ONLY. Worker release resolved from the release channel.",
      ).optional(),
      workerRelease: z.string().describe(
        "Output only. OUTPUT_ONLY. The release or release channel used to run the Build. This is set to the same value as `PrivatePoolV1Config.WorkerConfig.worker_release` for the UI to easily access.",
      ).optional(),
    }).describe(
      "Optional. Specification for execution on a `WorkerPool`. See [running builds in a private pool](https://cloud.google.com/build/docs/private-pools/run-builds-in-private-pool) for more information.",
    ).optional(),
    pubsubTopic: z.string().describe(
      "Optional. Option to specify the Pub/Sub topic to receive build status updates.",
    ).optional(),
    requestedVerifyOption: z.enum(["NOT_VERIFIED", "VERIFIED"]).describe(
      "Requested verifiability options.",
    ).optional(),
    resolvedWorkerRelease: z.string().describe(
      "Output only. Worker release resolved from the release channel.",
    ).optional(),
    secretEnv: z.array(z.string()).describe(
      "A list of global environment variables, which are encrypted using a Cloud Key Management Service crypto key. These values must be specified in the build's `Secret`. These variables will be available to all build steps in this build.",
    ).optional(),
    sourceProvenanceHash: z.array(
      z.enum([
        "NONE",
        "SHA256",
        "MD5",
        "GO_MODULE_H1",
        "SHA512",
        "DIRSUM_SHA256",
      ]),
    ).describe("Requested hash for SourceProvenance.").optional(),
    substitutionOption: z.enum(["MUST_MATCH", "ALLOW_LOOSE"]).describe(
      "Option to specify behavior when there is an error in the substitution checks. NOTE: this is always set to ALLOW_LOOSE for triggered builds and cannot be overridden in the build configuration file.",
    ).optional(),
    volumes: z.array(z.object({
      name: z.string().describe(
        "Name of the volume to mount. Volume names must be unique per build step and must be valid names for Docker volumes. Each named volume must be used by at least two build steps.",
      ).optional(),
      path: z.string().describe(
        "Path at which to mount the volume. Paths must be absolute and cannot conflict with other volume paths on the same build step or with certain reserved volume paths.",
      ).optional(),
    })).describe(
      "Global list of volumes to mount for ALL build steps Each volume is created as an empty volume prior to starting the build process. Upon completion of the build, volumes and their contents are discarded. Global volume names and paths cannot conflict with the volumes defined a build step. Using a global volume in a build with only one step is not valid as it is indicative of a build request with an incorrect configuration.",
    ).optional(),
    workerPool: z.string().describe(
      "This field deprecated; please use `pool.name` instead.",
    ).optional(),
    workerRelease: z.string().describe(
      "Optional. Option to specify which release or release channel (rapid|regular|stable) to use to run this build.",
    ).optional(),
  }).describe("Special options for this build.").optional(),
  projectId: z.string().describe("Output only. ID of the project.").optional(),
  queueTtl: z.string().describe(
    "TTL in queue for this build. If provided and the build is enqueued longer than this value, the build will expire and the build status will be `EXPIRED`. The TTL starts ticking from create_time.",
  ).optional(),
  secrets: z.array(z.object({
    kmsKeyName: z.string().describe(
      "Cloud KMS key name to use to decrypt these envs.",
    ).optional(),
    secretEnv: z.record(z.string(), z.string()).describe(
      "Map of environment variable name to its encrypted value. Secret environment variables must be unique across all of a build's secrets, and must be used by at least one build step. Values can be at most 64 KB in size. There can be at most 100 secret values across all of a build's secrets.",
    ).optional(),
  })).describe(
    "Secrets to decrypt using Cloud Key Management Service. Note: Secret Manager is the recommended technique for managing sensitive data with Cloud Build. Use `available_secrets` to configure builds to access secrets from Secret Manager. For instructions, see: https://cloud.google.com/cloud-build/docs/securing-builds/use-secrets",
  ).optional(),
  serviceAccount: z.string().describe(
    "IAM service account whose credentials will be used at build runtime. Must be of the format `projects/{PROJECT_ID}/serviceAccounts/{ACCOUNT}`. ACCOUNT can be email address or uniqueId of the service account.",
  ).optional(),
  source: z.object({
    connectedRepository: z.object({
      dir: z.string().describe(
        "Optional. Directory, relative to the source root, in which to run the build.",
      ).optional(),
      repository: z.string().describe(
        "Required. Name of the Google Cloud Build repository, formatted as `projects/*/locations/*/connections/*/repositories/*`.",
      ).optional(),
      revision: z.string().describe(
        "Required. The revision to fetch from the Git repository such as a branch, a tag, a commit SHA, or any Git ref.",
      ).optional(),
    }).describe(
      "Optional. If provided, get the source from this 2nd-gen Google Cloud Build repository resource.",
    ).optional(),
    developerConnectConfig: z.object({
      dir: z.string().describe(
        "Required. Directory, relative to the source root, in which to run the build.",
      ).optional(),
      gitRepositoryLink: z.string().describe(
        "Required. The Developer Connect Git repository link, formatted as `projects/*/locations/*/connections/*/gitRepositoryLink/*`.",
      ).optional(),
      revision: z.string().describe(
        "Required. The revision to fetch from the Git repository such as a branch, a tag, a commit SHA, or any Git ref.",
      ).optional(),
    }).describe(
      "If provided, get the source from this Developer Connect config.",
    ).optional(),
    gitSource: z.object({
      dir: z.string().describe(
        "Optional. Directory, relative to the source root, in which to run the build. This must be a relative path. If a step's `dir` is specified and is an absolute path, this value is ignored for that step's execution.",
      ).optional(),
      revision: z.string().describe(
        "Optional. The revision to fetch from the Git repository such as a branch, a tag, a commit SHA, or any Git ref. Cloud Build uses `git fetch` to fetch the revision from the Git repository; therefore make sure that the string you provide for `revision` is parsable by the command. For information on string values accepted by `git fetch`, see https://git-scm.com/docs/gitrevisions#_specifying_revisions. For information on `git fetch`, see https://git-scm.com/docs/git-fetch.",
      ).optional(),
      url: z.string().describe(
        "Required. Location of the Git repo to build. This will be used as a `git remote`, see https://git-scm.com/docs/git-remote.",
      ).optional(),
    }).describe("If provided, get the source from this Git repository.")
      .optional(),
    repoSource: z.object({
      branchName: z.string().describe(
        "Regex matching branches to build. The syntax of the regular expressions accepted is the syntax accepted by RE2 and described at https://github.com/google/re2/wiki/Syntax",
      ).optional(),
      commitSha: z.string().describe("Explicit commit SHA to build.")
        .optional(),
      dir: z.string().describe(
        "Optional. Directory, relative to the source root, in which to run the build. This must be a relative path. If a step's `dir` is specified and is an absolute path, this value is ignored for that step's execution.",
      ).optional(),
      invertRegex: z.boolean().describe(
        "Optional. Only trigger a build if the revision regex does NOT match the revision regex.",
      ).optional(),
      projectId: z.string().describe(
        "Optional. ID of the project that owns the Cloud Source Repository. If omitted, the project ID requesting the build is assumed.",
      ).optional(),
      repoName: z.string().describe(
        "Required. Name of the Cloud Source Repository.",
      ).optional(),
      substitutions: z.record(z.string(), z.string()).describe(
        "Optional. Substitutions to use in a triggered build. Should only be used with RunBuildTrigger",
      ).optional(),
      tagName: z.string().describe(
        "Regex matching tags to build. The syntax of the regular expressions accepted is the syntax accepted by RE2 and described at https://github.com/google/re2/wiki/Syntax",
      ).optional(),
    }).describe(
      "If provided, get the source from this location in a Cloud Source Repository.",
    ).optional(),
    storageSource: z.object({
      bucket: z.string().describe(
        "Cloud Storage bucket containing the source (see [Bucket Name Requirements](https://cloud.google.com/storage/docs/bucket-naming#requirements)).",
      ).optional(),
      generation: z.string().describe(
        "Optional. Cloud Storage generation for the object. If the generation is omitted, the latest generation will be used.",
      ).optional(),
      object: z.string().describe(
        "Required. Cloud Storage object containing the source. This object must be a zipped (`.zip`) or gzipped archive file (`.tar.gz`) containing source to build.",
      ).optional(),
      sourceFetcher: z.enum([
        "SOURCE_FETCHER_UNSPECIFIED",
        "GSUTIL",
        "GCS_FETCHER",
      ]).describe(
        "Optional. Option to specify the tool to fetch the source file for the build.",
      ).optional(),
    }).describe(
      "If provided, get the source from this location in Cloud Storage.",
    ).optional(),
    storageSourceManifest: z.object({
      bucket: z.string().describe(
        "Required. Cloud Storage bucket containing the source manifest (see [Bucket Name Requirements](https://cloud.google.com/storage/docs/bucket-naming#requirements)).",
      ).optional(),
      generation: z.string().describe(
        "Cloud Storage generation for the object. If the generation is omitted, the latest generation will be used.",
      ).optional(),
      object: z.string().describe(
        "Required. Cloud Storage object containing the source manifest. This object must be a JSON file.",
      ).optional(),
    }).describe(
      "If provided, get the source from this manifest in Cloud Storage. This feature is in Preview; see description [here](https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/gcs-fetcher).",
    ).optional(),
  }).describe("Optional. The location of the source files to build.")
    .optional(),
  steps: z.array(z.object({
    allowExitCodes: z.array(z.number().int()).describe(
      "Allow this build step to fail without failing the entire build if and only if the exit code is one of the specified codes. If allow_failure is also specified, this field will take precedence.",
    ).optional(),
    allowFailure: z.boolean().describe(
      "Allow this build step to fail without failing the entire build. If false, the entire build will fail if this step fails. Otherwise, the build will succeed, but this step will still have a failure status. Error information will be reported in the failure_detail field.",
    ).optional(),
    args: z.array(z.string()).describe(
      "A list of arguments that will be presented to the step when it is started. If the image used to run the step's container has an entrypoint, the `args` are used as arguments to that entrypoint. If the image does not define an entrypoint, the first element in args is used as the entrypoint, and the remainder will be used as arguments.",
    ).optional(),
    automapSubstitutions: z.boolean().describe(
      "Option to include built-in and custom substitutions as env variables for this build step. This option will override the global option in BuildOption.",
    ).optional(),
    dir: z.string().describe(
      "Working directory to use when running this step's container. If this value is a relative path, it is relative to the build's working directory. If this value is absolute, it may be outside the build's working directory, in which case the contents of the path may not be persisted across build step executions, unless a `volume` for that path is specified. If the build specifies a `RepoSource` with `dir` and a step with a `dir`, which specifies an absolute path, the `RepoSource` `dir` is ignored for the step's execution.",
    ).optional(),
    entrypoint: z.string().describe(
      "Entrypoint to be used instead of the build step image's default entrypoint. If unset, the image's default entrypoint is used.",
    ).optional(),
    env: z.array(z.string()).describe(
      'A list of environment variable definitions to be used when running a step. The elements are of the form "KEY=VALUE" for the environment variable "KEY" being given the value "VALUE".',
    ).optional(),
    exitCode: z.number().int().describe(
      "Output only. Return code from running the step.",
    ).optional(),
    id: z.string().describe(
      "Unique identifier for this build step, used in `wait_for` to reference this build step as a dependency.",
    ).optional(),
    name: z.string().describe(
      "Required. The name of the container image that will run this particular build step. If the image is available in the host's Docker daemon's cache, it will be run directly. If not, the host will attempt to pull the image first, using the builder service account's credentials if necessary. The Docker daemon's cache will already have the latest versions of all of the officially supported build steps ([https://github.com/GoogleCloudPlatform/cloud-builders](https://github.com/GoogleCloudPlatform/cloud-builders)). The Docker daemon will also have cached many of the layers for some popular images, like \"ubuntu\", \"debian\", but they will be refreshed at the time you attempt to use them. If you built an image in a previous build step, it will be stored in the host's Docker daemon's cache and is available to use as the name for a later build step.",
    ).optional(),
    pullTiming: z.object({
      endTime: z.string().describe("End of time span.").optional(),
      startTime: z.string().describe("Start of time span.").optional(),
    }).describe(
      "Output only. Stores timing information for pulling this build step's builder image only.",
    ).optional(),
    results: z.array(z.object({
      attestationContent: z.string().describe(
        "Optional. The content of the attestation to be generated.",
      ).optional(),
      attestationType: z.string().describe(
        "Optional. The type of attestation to be generated.",
      ).optional(),
      name: z.string().describe("Required. The name of the result.").optional(),
    })).describe("Declaration of results for this build step.").optional(),
    script: z.string().describe(
      "A shell script to be executed in the step. When script is provided, the user cannot specify the entrypoint or args.",
    ).optional(),
    secretEnv: z.array(z.string()).describe(
      "A list of environment variables which are encrypted using a Cloud Key Management Service crypto key. These values must be specified in the build's `Secret`.",
    ).optional(),
    status: z.enum([
      "STATUS_UNKNOWN",
      "PENDING",
      "QUEUED",
      "WORKING",
      "SUCCESS",
      "FAILURE",
      "INTERNAL_ERROR",
      "TIMEOUT",
      "CANCELLED",
      "EXPIRED",
    ]).describe(
      "Output only. Status of the build step. At this time, build step status is only updated on build completion; step status is not updated in real-time as the build progresses.",
    ).optional(),
    timeout: z.string().describe(
      "Time limit for executing this build step. If not defined, the step has no time limit and will be allowed to continue to run until either it completes or the build itself times out.",
    ).optional(),
    timing: z.object({
      endTime: z.string().describe("End of time span.").optional(),
      startTime: z.string().describe("Start of time span.").optional(),
    }).describe(
      "Output only. Stores timing information for executing this build step.",
    ).optional(),
    volumes: z.array(z.object({
      name: z.string().describe(
        "Name of the volume to mount. Volume names must be unique per build step and must be valid names for Docker volumes. Each named volume must be used by at least two build steps.",
      ).optional(),
      path: z.string().describe(
        "Path at which to mount the volume. Paths must be absolute and cannot conflict with other volume paths on the same build step or with certain reserved volume paths.",
      ).optional(),
    })).describe(
      "List of volumes to mount into the build step. Each volume is created as an empty volume prior to execution of the build step. Upon completion of the build, volumes and their contents are discarded. Using a named volume in only one step is not valid as it is indicative of a build request with an incorrect configuration.",
    ).optional(),
    waitFor: z.array(z.string()).describe(
      "The ID(s) of the step(s) that this build step depends on. This build step will not start until all the build steps in `wait_for` have completed successfully. If `wait_for` is empty, this build step will start when all previous build steps in the `Build.Steps` list have completed successfully.",
    ).optional(),
  })).describe("Required. The operations to be performed on the workspace.")
    .optional(),
  substitutions: z.record(z.string(), z.string()).describe(
    "Substitutions data for `Build` resource.",
  ).optional(),
  tags: z.array(z.string()).describe(
    "Tags for annotation of a `Build`. These are not docker tags.",
  ).optional(),
  timeout: z.string().describe(
    "Amount of time that this build should be allowed to run, to second granularity. If this amount of time elapses, work on the build will cease and the build status will be `TIMEOUT`. `timeout` starts ticking from `startTime`. Default time is 60 minutes.",
  ).optional(),
  parent: z.string().describe(
    "The parent resource where this build will be created. Format: `projects/{project}/locations/{location}`",
  ).optional(),
});

const _credentialKeys = new Set([
  "accessToken",
  "credentialsJson",
  "project",
  "scopes",
  "quotaProject",
  "apiEndpoint",
]);

function _buildGcpCredentials(
  g: Record<string, unknown>,
): ExplicitGcpCredentials {
  return {
    accessToken: g.accessToken as string | undefined,
    credentialsJson: g.credentialsJson as string | undefined,
    project: g.project as string | undefined,
    scopes: typeof g.scopes === "string"
      ? g.scopes.split(",").map((s: string) => s.trim())
      : undefined,
    quotaProject: g.quotaProject as string | undefined,
  };
}

/** Swamp extension model for Google Cloud Build Builds. Registered at `@swamp/gcp/cloudbuild/builds`. */
export const model = {
  type: "@swamp/gcp/cloudbuild/builds",
  version: "2026.09.26.1",
  upgrades: [
    {
      toVersion: "2026.07.29.1",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.08.12.2",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.08.23.1",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.08.25.1",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
    {
      toVersion: "2026.09.26.1",
      description: "No schema changes",
      upgradeAttributes: (old: Record<string, unknown>) => old,
    },
  ],
  globalArguments: GlobalArgsSchema,
  inputsSchema: InputsSchema,
  resources: {
    state: {
      description:
        "A build resource in the Cloud Build API. At a high level, a `Build` describes...",
      schema: StateSchema,
      lifetime: "infinite",
      garbageCollection: 10,
    },
  },
  methods: {
    create: {
      description: "Create a builds",
      arguments: z.object({}),
      execute: async (_args: Record<string, never>, context: any) => {
        const g = context.globalArgs;
        const baseUrl = g["apiEndpoint"]?.toString() ??
          Deno.env.get("GCP_API_ENDPOINT")?.trim() ?? BASE_URL;
        const credentials = _buildGcpCredentials(g);
        const projectId = await getProjectId(credentials);
        const params: Record<string, string> = { projectId: projectId };
        const body: Record<string, unknown> = {};
        if (g["artifacts"] !== undefined) body["artifacts"] = g["artifacts"];
        if (g["availableSecrets"] !== undefined) {
          body["availableSecrets"] = g["availableSecrets"];
        }
        if (g["dependencies"] !== undefined) {
          body["dependencies"] = g["dependencies"];
        }
        if (g["gitConfig"] !== undefined) body["gitConfig"] = g["gitConfig"];
        if (g["images"] !== undefined) body["images"] = g["images"];
        if (g["logsBucket"] !== undefined) body["logsBucket"] = g["logsBucket"];
        if (g["options"] !== undefined) body["options"] = g["options"];
        if (g["queueTtl"] !== undefined) body["queueTtl"] = g["queueTtl"];
        if (g["secrets"] !== undefined) body["secrets"] = g["secrets"];
        if (g["serviceAccount"] !== undefined) {
          body["serviceAccount"] = g["serviceAccount"];
        }
        if (g["source"] !== undefined) body["source"] = g["source"];
        if (g["steps"] !== undefined) body["steps"] = g["steps"];
        if (g["substitutions"] !== undefined) {
          body["substitutions"] = g["substitutions"];
        }
        if (g["tags"] !== undefined) body["tags"] = g["tags"];
        if (g["timeout"] !== undefined) body["timeout"] = g["timeout"];
        if (g["parent"] !== undefined) params["parent"] = String(g["parent"]);
        if (g["id"] !== undefined) params["id"] = String(g["id"]);
        const result = await createResource(
          baseUrl,
          INSERT_CONFIG,
          params,
          body,
          GET_CONFIG,
          undefined,
          undefined,
          credentials,
        ) as StateData;
        const instanceName = (g.name?.toString() ?? "current").replace(
          /[\/\\]/g,
          "_",
        ).replace(/\.\./g, "_").replace(/\0/g, "");
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    get: {
      description: "Get a builds",
      arguments: z.object({
        identifier: z.string().describe("The id of the builds"),
      }),
      execute: async (args: { identifier: string }, context: any) => {
        const g = context.globalArgs;
        const baseUrl = g["apiEndpoint"]?.toString() ??
          Deno.env.get("GCP_API_ENDPOINT")?.trim() ?? BASE_URL;
        const credentials = _buildGcpCredentials(g);
        const projectId = await getProjectId(credentials);
        const params: Record<string, string> = { projectId: projectId };
        params["id"] = args.identifier;
        const result = await readResource(
          baseUrl,
          GET_CONFIG,
          params,
          credentials,
        ) as StateData;
        const instanceName = (g.name?.toString() ?? args.identifier).replace(
          /[\/\\]/g,
          "_",
        ).replace(/\.\./g, "_").replace(/\0/g, "");
        const handle = await context.writeResource(
          "state",
          instanceName,
          result,
        );
        return { dataHandles: [handle] };
      },
    },
    sync: {
      description: "Sync builds state from GCP",
      arguments: z.object({
        identifier: z.string().describe(
          "Target a specific builds by id (e.g. one discovered by list)",
        ).optional(),
      }),
      execute: async (args: { identifier?: string }, context: any) => {
        const g = context.globalArgs;
        const baseUrl = g["apiEndpoint"]?.toString() ??
          Deno.env.get("GCP_API_ENDPOINT")?.trim() ?? BASE_URL;
        const credentials = _buildGcpCredentials(g);
        const projectId = await getProjectId(credentials);
        const instanceName =
          (g.name?.toString() ?? args.identifier ?? "current").replace(
            /[\/\\]/g,
            "_",
          ).replace(/\.\./g, "_").replace(/\0/g, "");
        const content = await context.dataRepository.getContent(
          context.modelType,
          context.modelId,
          instanceName,
        );
        if (!content) {
          throw new Error(
            "No existing state found - run create, get, or list first",
          );
        }
        const existing = JSON.parse(new TextDecoder().decode(content));
        try {
          const params: Record<string, string> = { projectId: projectId };
          const identifier = existing.id?.toString() ?? g["id"]?.toString();
          if (!identifier) {
            throw new Error(
              "No identifier found in existing state or globalArgs",
            );
          }
          params["id"] = identifier;
          const result = await readResource(
            baseUrl,
            GET_CONFIG,
            params,
            credentials,
          ) as StateData;
          const handle = await context.writeResource(
            "state",
            instanceName,
            result,
          );
          return { dataHandles: [handle] };
        } catch (error: unknown) {
          if (isResourceNotFoundError(error)) {
            const handle = await context.writeResource("state", instanceName, {
              status: "not_found",
              syncedAt: new Date().toISOString(),
            });
            return { dataHandles: [handle] };
          }
          throw error;
        }
      },
    },
    list: {
      description: "List builds resources",
      arguments: z.object({
        filter: z.string().describe(
          "The raw filter text to constrain the results.",
        ).optional(),
        pageSize: z.number().describe(
          "Number of results to return in the list.",
        ).optional(),
        parent: z.string().describe(
          "The parent of the collection of `Builds`. Format: `projects/{project}/locations/{location}`",
        ).optional(),
        maxPages: z.number().describe(
          "Maximum number of pages to fetch (default: 10)",
        ).optional(),
      }),
      execute: async (args: Record<string, unknown>, context: any) => {
        const g = context.globalArgs;
        const baseUrl = g["apiEndpoint"]?.toString() ??
          Deno.env.get("GCP_API_ENDPOINT")?.trim() ?? BASE_URL;
        const credentials = _buildGcpCredentials(g);
        const projectId = await getProjectId(credentials);
        const params: Record<string, string> = { projectId: projectId };
        if (args["filter"] !== undefined) {
          params["filter"] = String(args["filter"]);
        }
        if (args["pageSize"] !== undefined) {
          params["pageSize"] = String(args["pageSize"]);
        }
        if (args["parent"] !== undefined) {
          params["parent"] = String(args["parent"]);
        }
        const { items, nextPageToken } = await listResources(
          baseUrl,
          LIST_CONFIG,
          params,
          "builds",
          (args.maxPages as number | undefined) ?? 10,
          credentials,
        );
        const dataHandles = [];
        for (let i = 0; i < items.length; i++) {
          const item = items[i] as StateData;
          const instanceName = (item.id?.toString() ?? String(i)).replace(
            /[\/\\]/g,
            "_",
          ).replace(/\.\./g, "_").replace(/\0/g, "");
          const handle = await context.writeResource(
            "state",
            instanceName,
            item,
          );
          dataHandles.push(handle);
        }
        return { dataHandles, result: { count: items.length, nextPageToken } };
      },
    },
    approve: {
      description: "approve",
      arguments: z.object({
        approvalResult: z.any().optional(),
      }),
      execute: async (args: Record<string, unknown>, context: any) => {
        const g = context.globalArgs;
        const baseUrl = g["apiEndpoint"]?.toString() ??
          Deno.env.get("GCP_API_ENDPOINT")?.trim() ?? BASE_URL;
        const credentials = _buildGcpCredentials(g);
        const projectId = await getProjectId(credentials);
        const params: Record<string, string> = { projectId: projectId };
        if (g["name"] !== undefined) params["name"] = String(g["name"]);
        const body: Record<string, unknown> = {};
        if (args["approvalResult"] !== undefined) {
          body["approvalResult"] = args["approvalResult"];
        }
        const result = await createResource(
          baseUrl,
          {
            "id": "cloudbuild.projects.builds.approve",
            "path": "v1/{+name}:approve",
            "httpMethod": "POST",
            "parameterOrder": ["name"],
            "parameters": { "name": { "location": "path", "required": true } },
          },
          params,
          body,
          undefined,
          undefined,
          undefined,
          credentials,
        );
        return { result };
      },
    },
    cancel: {
      description: "cancel",
      arguments: z.object({
        id: z.any().optional(),
        name: z.any().optional(),
        projectId: z.any().optional(),
      }),
      execute: async (args: Record<string, unknown>, context: any) => {
        const g = context.globalArgs;
        const baseUrl = g["apiEndpoint"]?.toString() ??
          Deno.env.get("GCP_API_ENDPOINT")?.trim() ?? BASE_URL;
        const credentials = _buildGcpCredentials(g);
        const projectId = await getProjectId(credentials);
        const params: Record<string, string> = { projectId: projectId };
        const content = await context.dataRepository.getContent(
          context.modelType,
          context.modelId,
          (g.name?.toString() ?? "current").replace(/[\/\\]/g, "_").replace(
            /\.\./g,
            "_",
          ).replace(/\0/g, ""),
        );
        if (!content) {
          throw new Error("No existing state found - run create or get first");
        }
        const existing = JSON.parse(new TextDecoder().decode(content));
        params["id"] = existing["id"]?.toString() ?? g["id"]?.toString() ?? "";
        const body: Record<string, unknown> = {};
        if (args["id"] !== undefined) body["id"] = args["id"];
        if (args["name"] !== undefined) body["name"] = args["name"];
        if (args["projectId"] !== undefined) {
          body["projectId"] = args["projectId"];
        }
        const result = await createResource(
          baseUrl,
          {
            "id": "cloudbuild.projects.builds.cancel",
            "path": "v1/projects/{projectId}/builds/{id}:cancel",
            "httpMethod": "POST",
            "parameterOrder": ["projectId", "id"],
            "parameters": {
              "id": { "location": "path", "required": true },
              "projectId": { "location": "path", "required": true },
            },
          },
          params,
          body,
          undefined,
          undefined,
          undefined,
          credentials,
        );
        return { result };
      },
    },
    retry: {
      description: "retry",
      arguments: z.object({
        id: z.any().optional(),
        name: z.any().optional(),
        projectId: z.any().optional(),
      }),
      execute: async (args: Record<string, unknown>, context: any) => {
        const g = context.globalArgs;
        const baseUrl = g["apiEndpoint"]?.toString() ??
          Deno.env.get("GCP_API_ENDPOINT")?.trim() ?? BASE_URL;
        const credentials = _buildGcpCredentials(g);
        const projectId = await getProjectId(credentials);
        const params: Record<string, string> = { projectId: projectId };
        const content = await context.dataRepository.getContent(
          context.modelType,
          context.modelId,
          (g.name?.toString() ?? "current").replace(/[\/\\]/g, "_").replace(
            /\.\./g,
            "_",
          ).replace(/\0/g, ""),
        );
        if (!content) {
          throw new Error("No existing state found - run create or get first");
        }
        const existing = JSON.parse(new TextDecoder().decode(content));
        params["id"] = existing["id"]?.toString() ?? g["id"]?.toString() ?? "";
        const body: Record<string, unknown> = {};
        if (args["id"] !== undefined) body["id"] = args["id"];
        if (args["name"] !== undefined) body["name"] = args["name"];
        if (args["projectId"] !== undefined) {
          body["projectId"] = args["projectId"];
        }
        const result = await createResource(
          baseUrl,
          {
            "id": "cloudbuild.projects.builds.retry",
            "path": "v1/projects/{projectId}/builds/{id}:retry",
            "httpMethod": "POST",
            "parameterOrder": ["projectId", "id"],
            "parameters": {
              "id": { "location": "path", "required": true },
              "projectId": { "location": "path", "required": true },
            },
          },
          params,
          body,
          undefined,
          undefined,
          undefined,
          credentials,
        );
        return { result };
      },
    },
  },
};
